"""
AgencyOS API Routers Package
============================
Tất cả routers cho backend API.
"""

from . import (
    accounting,
    agents,
    agents_creator,
    analytics,
    audit,
    campaigns,
    commands,
    crm,
    franchise,
    gumroad_webhooks,
    hr,
    i18n,
    inventory,
    kanban,
    monitor,
    ops,
    payments,
    paypal_webhooks,
    router,
    scheduler,
    stripe_webhooks,
    swarm,
    vibes,
    vietnam,
    workflow,
)

__all__ = [
    "accounting",
    "agents",
    "analytics",
    "campaigns",
    "commands",
    "crm",
    "franchise",
    "hr",
    "i18n",
    "inventory",
    "payments",
    "router",
    "scheduler",
    "vibes",
    "vietnam",
    "monitor",
    "workflow",
    "agents_creator",
    "swarm",
    "audit",
    "paypal_webhooks",
    "stripe_webhooks",
    "gumroad_webhooks",
    "kanban",
    "ops",
]
