module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/*.test.ts'],
  moduleDirectories: ['node_modules', '<rootDir>/node_modules'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@agencyos/trading-core/(.*)$': '<rootDir>/../../packages/trading-core/$1',
    '^@agencyos/trading-core$': '<rootDir>/../../packages/trading-core/index.ts',
    '^@agencyos/vibe-arbitrage-engine/(.*)$': '<rootDir>/../../packages/vibe-arbitrage-engine/$1',
    '^@agencyos/vibe-arbitrage-engine$': '<rootDir>/../../packages/vibe-arbitrage-engine/index.ts',
    '^@agencyos/vibe-billing-trading/(.*)$': '<rootDir>/../../packages/vibe-billing-trading/$1',
    '^@agencyos/vibe-billing-trading$': '<rootDir>/../../packages/vibe-billing-trading/index.ts',
  },
  transform: {
    '^.+\\.ts$': ['ts-jest', {
      tsconfig: '<rootDir>/tsconfig.json',
      diagnostics: false,
    }],
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.test.ts',
    '!src/index.ts',
    '!src/cli/**',
    '!src/data/**',
    '!src/ui/**',
    '!src/reporting/**',
    '!src/arbitrage/index.ts',
    '!src/core/RewardFunction.ts',
    '!src/core/SignalGenerator.ts',
    '!src/core/StrategyEnsemble.ts',
    '!src/core/StrategyLoader.ts',
    '!src/core/strategy-marketplace.ts',
    '!src/core/tenant-strategy-manager.ts',
    '!src/core/bot-engine-config-and-state-types.ts',
    '!src/backtest/BacktestRunner.ts',
    '!src/backtest/BacktestOptimizer.ts',
    '!src/backtest/backtest-engine-result-types.ts',
    '!src/interfaces/**',
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 80,
      statements: 80,
    },
  },
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  coverageReporters: ['text', 'text-summary', 'lcov'],
};
