name = "algo-trader-worker"
main = "dist/worker/api/gateway.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# KV namespace for build cache
[[kv_namespaces]]
binding = "BUILD_CACHE"
id = "95df9f174767429ea6e4d2e8c63c982a"

[env.staging]
name = "algo-trader-staging"

[env.staging.vars]
NODE_ENV = "staging"

[[env.staging.kv_namespaces]]
binding = "BUILD_CACHE"
id = "95df9f174767429ea6e4d2e8c63c982a"
