/**
 * FPGA Accelerator — mock PCIe-attached FPGA interface for ultra-low latency order signing.
 * In production: mmap PCIe BAR registers and DMA ring buffers via UIO/VFIO driver.
 * Mock: returns constant latency and deterministic signed packets in-process.
 * Default disabled/dry-run mode; no real hardware access.
 */

import { createHash, randomBytes } from 'crypto';

export interface FpgaAcceleratorConfig {
  /** Dry-run mode — simulate FPGA without real PCIe access. */
  dryRun: boolean;
  /** PCIe device path (e.g. /dev/uio0). */
  devicePath: string;
  /** Simulated fixed FPGA processing latency in nanoseconds. */
  fixedLatencyNs: number;
  /** Firmware version string loaded on the FPGA. */
  firmwareVersion: string;
}

export interface FpgaPacket {
  /** Unique packet sequence number. */
  seq: number;
  /** Payload bytes (order data). */
  payload: Buffer;
  /** HMAC-SHA256 signature generated by mock FPGA logic. */
  signature: string;
  /** Timestamp of packet generation (Unix ms). */
  generatedAt: number;
  /** Simulated PCIe round-trip latency in ns. */
  latencyNs: number;
}

const DEFAULT_CONFIG: FpgaAcceleratorConfig = {
  dryRun: true,
  devicePath: '/dev/uio0',
  fixedLatencyNs: 800,
  firmwareVersion: '1.0.0-mock',
};

/** 32-byte internal signing key (zero-filled for dev/mock). */
const MOCK_SIGNING_KEY = Buffer.alloc(32, 0xab);

export class FpgaAccelerator {
  private readonly cfg: FpgaAcceleratorConfig;
  private initialized = false;
  private seqCounter = 0;
  private packetCount = 0;

  constructor(config: Partial<FpgaAcceleratorConfig> = {}) {
    this.cfg = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * Initialize FPGA over PCIe (mock: validates config, sets initialized flag).
   * Must be called before signPacket / generatePacket.
   */
  initialize(): void {
    if (!this.cfg.devicePath) {
      throw new Error('FPGA device path must be specified');
    }
    this.initialized = true;
  }

  /**
   * Sign a raw payload using mock FPGA HMAC logic.
   * Returns hex-encoded signature deterministic on (key XOR payload).
   * Throws if not initialized.
   */
  signPacket(payload: Buffer): string {
    this.assertInitialized();
    // Mock: HMAC-SHA256 with fixed key
    return createHash('sha256')
      .update(Buffer.concat([MOCK_SIGNING_KEY, payload]))
      .digest('hex');
  }

  /**
   * Generate a fully signed FpgaPacket from raw order bytes.
   * Increments sequence counter and records simulated latency.
   */
  generatePacket(payload: Buffer): FpgaPacket {
    this.assertInitialized();
    const seq = ++this.seqCounter;
    this.packetCount++;

    const packet: FpgaPacket = {
      seq,
      payload,
      signature: this.signPacket(payload),
      generatedAt: Date.now(),
      latencyNs: this.cfg.fixedLatencyNs,
    };

    return packet;
  }

  /**
   * Return the configured fixed FPGA processing latency in nanoseconds.
   * In production: read from PCIe timestamp registers.
   */
  getLatencyNs(): number {
    return this.cfg.fixedLatencyNs;
  }

  isInitialized(): boolean {
    return this.initialized;
  }

  getPacketCount(): number {
    return this.packetCount;
  }

  getSeqCounter(): number {
    return this.seqCounter;
  }

  getFirmwareVersion(): string {
    return this.cfg.firmwareVersion;
  }

  getConfig(): FpgaAcceleratorConfig {
    return { ...this.cfg };
  }

  private assertInitialized(): void {
    if (!this.initialized) {
      throw new Error('FpgaAccelerator must be initialized before use');
    }
  }
}
