#!/bin/bash
# FACTORY LOOP v13.1 — CTO Brain v3 + watchdog + daily digest
# State-aware dispatch + cascade bridge + ROI learning + auto-restart
# Date: 2026-03-16 | agencyos.network architecture
set -euo pipefail

TMUX_SESSION="tom_hum"
PANES=(0 1)
PANE_PROJECTS=("sophia-proposal" "well")
PANE_DIRS=("apps/sophia-proposal" "apps/well")
PANE_NAMES=("Sophia AI Video Factory" "WellNexus Healthcare B2B")
SLEEP_INTERVAL=120
COMMAND_TIMEOUT=600  # 10 min max per command before considered hung
METRICS_LOG="/tmp/factory-metrics.log"
PID_FILE="/tmp/factory.pid"
DAILY_DIGEST_DIR="$HOME/mekong-cli/plans/reports"

# Write PID file for watchdog
echo $$ > "$PID_FILE"

# CASCADE STATE FILES
PANE_STATE_DIR="/tmp/pane_state"
mkdir -p "$PANE_STATE_DIR"

# ═══════════════════════════════════════════════════════════════
# TRAP + CLEANUP — Kill zombie processes on exit
# ═══════════════════════════════════════════════════════════════
cleanup() {
  echo "🧹 [$(date +%T)] FACTORY SHUTDOWN — cleaning up zombies..."
  pkill -f "node.*jest" 2>/dev/null || true
  pkill -f "node.*vitest" 2>/dev/null || true
  pkill -f "tsserver.js" 2>/dev/null || true
  rm -f /tmp/cto_cooldown_P* 2>/dev/null || true
  rm -f /tmp/cto_dispatch_ts_P* 2>/dev/null || true
  rm -f "$PID_FILE" 2>/dev/null || true
  log_metric "factory_shutdown" "clean" "0"
  # Write daily digest on shutdown
  write_daily_digest
  echo "🏭 FACTORY STOPPED — $(date)"
}
trap cleanup EXIT INT TERM HUP

# ═══════════════════════════════════════════════════════════════
# DAILY DIGEST — Summarize factory activity to reports/
# ═══════════════════════════════════════════════════════════════
write_daily_digest() {
  local TODAY=$(date +%y%m%d)
  local DIGEST_FILE="${DAILY_DIGEST_DIR}/factory-daily-${TODAY}.md"
  mkdir -p "$DAILY_DIGEST_DIR"

  if [ ! -f "$METRICS_LOG" ]; then
    return
  fi

  local TODAY_ISO=$(date +%Y-%m-%d)
  local TODAY_LINES=$(grep "^${TODAY_ISO}" "$METRICS_LOG" 2>/dev/null || true)

  if [ -z "$TODAY_LINES" ]; then
    return
  fi

  local DISPATCHES=$(echo "$TODAY_LINES" | grep -c "dispatch" || echo "0")
  local SUCCESSES=$(echo "$TODAY_LINES" | grep -c "command_complete.*success" || echo "0")
  local TIMEOUTS=$(echo "$TODAY_LINES" | grep -c "command_timeout" || echo "0")
  local CRASHES=$(echo "$TODAY_LINES" | grep -c "crash" || echo "0")
  local UNKNOWNS=$(echo "$TODAY_LINES" | grep -c "unknown_state" || echo "0")

  cat > "$DIGEST_FILE" << DIGEST
# Factory Daily Digest — ${TODAY_ISO}

## Summary
- Dispatches: ${DISPATCHES}
- Successes: ${SUCCESSES}
- Timeouts: ${TIMEOUTS}
- Crashes: ${CRASHES}
- Unknown states: ${UNKNOWNS}
- Success rate: $([ "$DISPATCHES" -gt 0 ] && echo "$((SUCCESSES * 100 / DISPATCHES))%" || echo "N/A")

## Per-Project
$(echo "$TODAY_LINES" | grep "dispatch" | awk -F'|' '{gsub(/^ +| +$/,"",$4); print $4}' | sort | uniq -c | sort -rn | head -5 | while read count proj; do echo "- ${proj}: ${count} dispatches"; done)

## Last 10 Events
$(echo "$TODAY_LINES" | tail -10 | awk -F'|' '{gsub(/^ +| +$/,"",$1); gsub(/^ +| +$/,"",$2); gsub(/^ +| +$/,"",$4); printf "- %s %s %s\n", $1, $2, $4}')

---
*Auto-generated by factory-loop.sh v13.1*
DIGEST

  echo "📋 Daily digest written: $DIGEST_FILE"
}

# ═══════════════════════════════════════════════════════════════
# METRICS LOGGING — Append to /tmp/factory-metrics.log
# Format: ISO_TIMESTAMP | event | pane | project | status | duration_s | command
# ═══════════════════════════════════════════════════════════════
log_metric() {
  local EVENT=$1 STATUS=$2 DURATION=${3:-0} PANE=${4:-"-"} PROJECT=${5:-"-"} CMD=${6:-"-"}
  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) | ${EVENT} | P${PANE} | ${PROJECT} | ${STATUS} | ${DURATION}s | ${CMD:0:80}" >> "$METRICS_LOG"
}

# ═══════════════════════════════════════════════════════════════
# HEALTH CHECK — Verify pane is responsive before dispatch
# Returns 0 if healthy, 1 if unhealthy
# ═══════════════════════════════════════════════════════════════
check_pane_health() {
  local PANE=$1

  # 1. Verify tmux pane exists
  if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "💀 [P$PANE] tmux session '$TMUX_SESSION' not found"
    log_metric "health_check" "session_dead" "0" "$PANE"
    return 1
  fi

  # 2. Verify pane is alive (can capture output)
  local CAPTURE
  CAPTURE=$(tmux capture-pane -t "$TMUX_SESSION:0.$PANE" -p 2>/dev/null) || {
    echo "💀 [P$PANE] pane capture failed — pane dead"
    log_metric "health_check" "pane_dead" "0" "$PANE"
    return 1
  }

  # 3. Check for known fatal states
  local TAIL3=$(echo "$CAPTURE" | tail -n 3)
  if echo "$TAIL3" | grep -qE "Segmentation fault|killed|SIGKILL|core dumped"; then
    echo "💀 [P$PANE] fatal crash detected"
    log_metric "health_check" "fatal_crash" "0" "$PANE"
    return 1
  fi

  return 0
}

# ═══════════════════════════════════════════════════════════════
# HUNG COMMAND DETECTION — Kill commands stuck >10 min
# ═══════════════════════════════════════════════════════════════
check_command_timeout() {
  local PANE=$1 PROJECT=$2
  local TS_FILE="/tmp/cto_dispatch_ts_P${PANE}"
  local NOW=$(date +%s)

  if [ ! -f "$TS_FILE" ]; then
    return 0  # No active command
  fi

  local DISPATCH_TS=$(cat "$TS_FILE" 2>/dev/null || echo "0")
  local ELAPSED=$((NOW - DISPATCH_TS))

  if [ "$ELAPSED" -gt "$COMMAND_TIMEOUT" ]; then
    echo "⏰ [P$PANE] TIMEOUT: command hung for ${ELAPSED}s (>${COMMAND_TIMEOUT}s) — sending Escape+Enter"
    log_metric "command_timeout" "hung" "$ELAPSED" "$PANE" "$PROJECT"
    # Send Escape to cancel, then Enter to get back to prompt
    tmux send-keys -t "$TMUX_SESSION:0.$PANE" Escape
    sleep 1
    tmux send-keys -t "$TMUX_SESSION:0.$PANE" Enter
    rm -f "$TS_FILE"
    return 1
  fi

  return 0
}

# Mark command dispatched (start timer)
mark_dispatch_start() {
  local PANE=$1
  date +%s > "/tmp/cto_dispatch_ts_P${PANE}"
}

# Mark command completed (clear timer)
mark_dispatch_done() {
  local PANE=$1
  rm -f "/tmp/cto_dispatch_ts_P${PANE}"
}

echo "🏭 FACTORY v13.0 — CTO BRAIN v3 + CASCADE + PRIORITY — $(date) — PID: $$"
echo "👑 Brain learning + analysis→code cascade + ROI priority queue"
echo "🏛️ P0=${PANE_PROJECTS[0]}, P1=${PANE_PROJECTS[1]}"
echo "📊 Metrics: $METRICS_LOG"
log_metric "factory_start" "ok" "0"

# Load brain learning state on startup
BRAIN_STATE_FILE="$HOME/mekong-cli/apps/openclaw-worker/brain-learning-state.json"
if [ -f "$BRAIN_STATE_FILE" ]; then
  LEARNED_CMDS=$(timeout 3 node -e "
    const s = JSON.parse(require('fs').readFileSync('$BRAIN_STATE_FILE','utf-8'));
    console.log(Object.keys(s.commandEffectiveness || {}).length);
  " 2>/dev/null || echo "0")
  echo "🧠 Brain loaded: ${LEARNED_CMDS} commands learned from past sessions"
else
  echo "🧠 Brain: fresh start (no learning data yet)"
fi

# Save/load previous command output per pane (for A→B chaining)
save_pane_output() {
  local PANE=$1
  local OUTPUT=$2
  # Save last 20 meaningful lines as context for next command
  echo "$OUTPUT" | grep -v "^$" | grep -v "^─" | grep -v "bypass permissions" | grep -v "qwen" | tail -20 > "$PANE_STATE_DIR/pane_${PANE}_output"
}

get_prev_output() {
  local PANE=$1
  cat "$PANE_STATE_DIR/pane_${PANE}_output" 2>/dev/null || echo "(no previous output)"
}

# ═══════════════════════════════════════════════════════════════
# CASCADE LOGIC — Reads output, chains commands
# ═══════════════════════════════════════════════════════════════

# Cascade state per pane: tracks what needs to happen next
# Values: "needs_bootstrap" | "needs_portfolio" | "ready_operate" | "needs_fix"

get_pane_state() {
  local PANE=$1
  local STATE_FILE="$PANE_STATE_DIR/pane_${PANE}_state"
  cat "$STATE_FILE" 2>/dev/null || echo "ready_operate"
}

set_pane_state() {
  local PANE=$1
  local STATE=$2
  echo "$STATE" > "$PANE_STATE_DIR/pane_${PANE}_state"
}

# Analyze last 45 lines for cascade triggers
# Returns: "bootstrap" | "fix" | "analysis_done" | "continue"
analyze_output() {
  local OUTPUT="$1"
  local OUTPUT_LOWER=$(echo "$OUTPUT" | tr '[:upper:]' '[:lower:]')

  # Priority 1: SUCCESS signals → project is ready, continue rotation
  if echo "$OUTPUT_LOWER" | grep -qE "✅|bootstrap complete|ready for|initialized|success|completed|saved|created|done|finished|launched|deployed|operational"; then
    # CASCADE BRIDGE: detect if output is analysis/report (not code)
    # If last command produced analysis → trigger engineering /cook next
    if echo "$OUTPUT_LOWER" | grep -qE "report saved|analysis complete|terrain.*score|thesis.*updated|momentum.*score|five.factor|market.*analysis|content.*plan"; then
      echo "analysis_done"
      return
    fi
    echo "continue"
    return
  fi

  # Priority 2: Critical errors → needs fix
  if echo "$OUTPUT_LOWER" | grep -qE "error:|failed:|exception|traceback|crashed|fatal:"; then
    echo "fix"
    return
  fi

  # Priority 3: Not initialized → needs bootstrap
  if echo "$OUTPUT_LOWER" | grep -qE "not initialized|does not exist|not configured|no studio found|missing portfolio|missing studio"; then
    echo "bootstrap"
    return
  fi

  # Default: continue rotation
  echo "continue"
}

# Get cascade command based on state and output analysis
get_cascade_command() {
  local PANE=$1
  local PROJECT=$2
  local DIR=$3
  local NAME=$4
  local OUTPUT="$5"

  local CURRENT_STATE=$(get_pane_state "$PANE")
  local ANALYSIS=$(analyze_output "$OUTPUT")

  # Log analysis to stderr (not captured in command output)
  echo "   📊 State='$CURRENT_STATE' Analysis='$ANALYSIS'" >&2

  # OVERRIDE: If analysis says fix/bootstrap/analysis_done, handle immediately
  if [ "$ANALYSIS" = "fix" ]; then
    set_pane_state "$PANE" "needs_fix"
    echo "/cook [CHỈ project: ${PROJECT}] [DIR: ${DIR}] Fix errors in $NAME — KHÔNG đụng project khác"
    return
  fi

  if [ "$ANALYSIS" = "bootstrap" ]; then
    set_pane_state "$PANE" "needs_bootstrap"
    echo "/studio-bootstrap [CHỈ project: ${PROJECT}] [DIR: ${DIR}] $NAME — KHÔNG đụng project khác"
    return
  fi

  # CASCADE BRIDGE: analysis → code. This is the missing link!
  # When Studio/Business output analysis, AUTO-TRIGGER /cook to produce real code
  if [ "$ANALYSIS" = "analysis_done" ]; then
    echo "   🌉 CASCADE: analysis → engineering /cook" >&2
    # Try brain learning for best command
    local BEST_CMD
    BEST_CMD=$(timeout 3 node -e "
      try {
        const r = require('$HOME/mekong-cli/apps/openclaw-worker/lib/factory-roi-calculator');
        const cmd = r.getBestCommand('$PROJECT', 'deployed');
        if (cmd) console.log(cmd); else console.log('');
      } catch(e) { console.log(''); }
    " 2>/dev/null || echo "")

    if [ -n "$BEST_CMD" ] && [ ${#BEST_CMD} -gt 3 ]; then
      echo "${BEST_CMD} [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
    else
      # Default cascade: build feature based on analysis context
      echo "/cook Build the next feature for ${NAME} based on latest analysis. Read plans/reports/ for context. Write TypeScript code to src/. [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
    fi
    return
  fi

  # State machine: chain commands logically
  case "$CURRENT_STATE" in
    "needs_bootstrap")
      # Just set bootstrap, next iteration will check output
      set_pane_state "$PANE" "needs_portfolio"
      echo "/studio-bootstrap [CHỈ project: ${PROJECT}] [DIR: ${DIR}] $NAME — KHÔNG đụng project khác"
      ;;
    "needs_portfolio")
      # Check if bootstrap succeeded
      if echo "$OUTPUT" | grep -qE "success|completed|saved"; then
        set_pane_state "$PANE" "ready_operate"
        echo "/portfolio-create [CHỈ project: ${PROJECT}] [DIR: ${DIR}] $NAME — KHÔNG đụng project khác"
      else
        # Bootstrap failed, retry
        echo "/studio-bootstrap [CHỈ project: ${PROJECT}] [DIR: ${DIR}] $NAME — KHÔNG đụng project khác"
      fi
      ;;
    "ready_operate")
      # Normal operation mode — use rotation
      local ROTATION_CMD=$(get_next_command "$PANE" "$PROJECT" "$DIR" "$NAME")
      echo "$ROTATION_CMD"
      ;;
    *)
      # Unknown state → bootstrap first
      set_pane_state "$PANE" "needs_bootstrap"
      echo "/studio-bootstrap $NAME — Thư mục: ${DIR}"
      ;;
  esac
}

# ═══════════════════════════════════════════════════════════════
# PROJECT STATE DETECTION — Checks actual files on disk
# States: empty → scaffolded → built → deployed → operating
# ═══════════════════════════════════════════════════════════════

detect_project_state() {
  local DIR=$1
  local FULL_DIR="$HOME/mekong-cli/${DIR}"

  # Directory doesn't exist at all
  if [ ! -d "$FULL_DIR" ]; then
    echo "empty"
    return
  fi

  # No src/ or app/ = empty project (only config files)
  if [ ! -d "${FULL_DIR}/src" ] && [ ! -d "${FULL_DIR}/app" ]; then
    echo "empty"
    return
  fi

  # Has src but no node_modules = needs install
  if [ ! -d "${FULL_DIR}/node_modules" ]; then
    echo "needs_install"
    return
  fi

  # Has build output = deployed/built
  if [ -d "${FULL_DIR}/out" ] || [ -d "${FULL_DIR}/.next" ] || [ -d "${FULL_DIR}/dist" ]; then
    echo "deployed"
    return
  fi

  # Has src + node_modules but no build = scaffolded, needs features
  echo "scaffolded"
}

# ═══════════════════════════════════════════════════════════════
# OPERATE COMMANDS — Only used when project is deployed/live
# ═══════════════════════════════════════════════════════════════

# Feature build commands for scaffolded projects
FEATURE_CMDS_TEMPLATE=(
  "Build landing page with hero section, features grid, and pricing tiers"
  "Build user dashboard with authentication and stats cards"
  "Build billing integration with Polar.sh webhooks and credit system"
  "Build API routes for core product functionality"
)

# Operate commands for deployed projects (business/studio layer)
OPERATE_CMDS_TEMPLATE=(
  "/studio-operate-daily"
  "/marketing-content-engine"
  "/sales-pipeline-build"
  "/portfolio-status"
)

# Code generation commands for deployed projects wanting new algorithms
ALGO_CMDS=(
  "/cook Implement a scoring algorithm. Write TypeScript to src/algorithms/scoring-engine.ts with: interface, scoring logic, unit tests, and export."
  "/cook Implement a pricing engine. Write TypeScript to src/algorithms/pricing-engine.ts with: tiered pricing, discount calc, bundle pricing."
  "/cook Implement a recommendation algorithm. Write TypeScript to src/algorithms/recommendation-engine.ts with: collaborative filtering, content matching."
  "/cook Build a revenue forecasting model. Write TypeScript to src/algorithms/revenue-forecast.ts with: MRR projection, cohort analysis."
  "/cook Build a unit economics calculator. Write TypeScript to src/algorithms/unit-economics.ts with: LTV, CAC payback, gross margin."
  "/cook Build an A/B test engine. Write TypeScript to src/algorithms/ab-test-engine.ts with: significance calculator, sample size estimator."
  "/cook Build a feature prioritizer (RICE/ICE). Write TypeScript to src/algorithms/feature-prioritizer.ts with: multi-framework scorer."
)

get_next_command() {
  local PANE=$1
  local PROJECT=$2
  local DIR=$3
  local NAME=$4

  # Detect actual project state from filesystem
  local PROJECT_STATE=$(detect_project_state "$DIR")
  echo "   🔍 Project state: $PROJECT_STATE" >&2

  case "$PROJECT_STATE" in
    "empty")
      # Project has no code — scaffold first!
      echo "/raas-scaffold ${PROJECT} --type saas --stack next+cf [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
      ;;
    "needs_install")
      # Has code but no deps — install and build
      echo "/cook Install dependencies and build: cd ${DIR} && pnpm install && pnpm build [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
      ;;
    "scaffolded")
      # Has code + deps but no build — build features one by one
      local FEATURE_IDX_FILE="/tmp/feature_idx_${PROJECT}"
      local FEATURE_IDX=$(cat "$FEATURE_IDX_FILE" 2>/dev/null || echo "0")
      local TOTAL=${#FEATURE_CMDS_TEMPLATE[@]}

      if [ "$FEATURE_IDX" -lt "$TOTAL" ]; then
        local FEATURE="${FEATURE_CMDS_TEMPLATE[$FEATURE_IDX]}"
        echo $((FEATURE_IDX + 1)) > "$FEATURE_IDX_FILE"
        echo "/cook ${FEATURE} for ${NAME} [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
      else
        # All features built — try to build/deploy
        echo "/cook Run pnpm build and verify no errors [CHỈ project: ${PROJECT}] [DIR: ${DIR}]"
      fi
      ;;
    "deployed")
      # Project is live — NOW use business/studio/algo commands
      local AI_CMD=""
      local STATE_FILE="$PANE_STATE_DIR/pane_${PANE}_output"

      # Try BytePlus brain first
      AI_CMD=$(timeout 10 node ~/mekong-cli/byteplus-cto-brain.js "$PROJECT" "$STATE_FILE" 2>/dev/null || true)

      # Fallback: alternate between operate cmds and algo cmds
      if [ -z "$AI_CMD" ] || [ ${#AI_CMD} -lt 3 ]; then
        local IDX_FILE="/tmp/cto_cmd_idx_P${PANE}"
        local IDX=$(cat "$IDX_FILE" 2>/dev/null || echo "0")

        # Even iterations: operate commands, odd: algo commands
        if [ $((IDX % 2)) -eq 0 ]; then
          local OP_IDX=$(( (IDX / 2) % ${#OPERATE_CMDS_TEMPLATE[@]} ))
          AI_CMD="${OPERATE_CMDS_TEMPLATE[$OP_IDX]} ${NAME}"
        else
          local ALGO_IDX=$(( (IDX / 2) % ${#ALGO_CMDS[@]} ))
          AI_CMD="${ALGO_CMDS[$ALGO_IDX]}"
        fi
        echo $(( (IDX + 1) )) > "$IDX_FILE"
      fi

      echo "${AI_CMD} [CHỈ project: ${PROJECT}] [DIR: ${DIR}] — KHÔNG đụng project khác."
      ;;
  esac
}

# ═══════════════════════════════════════════════════════════════
# ROI-AWARE LEARNING — Record outcomes, learn what works
# ═══════════════════════════════════════════════════════════════
record_outcome() {
  local PROJECT=$1 STATE=$2 CMD=$3 SUCCESS=$4 DURATION=$5
  timeout 5 node -e "
    try {
      const r = require('$HOME/mekong-cli/apps/openclaw-worker/lib/factory-roi-calculator');
      r.recordCommandOutcome('$PROJECT', '$STATE', '$(echo "$CMD" | head -c 60)', $SUCCESS, $DURATION);
    } catch(e) {}
  " 2>/dev/null || true
}

# Check if a command should be avoided based on past failures
should_avoid() {
  local PROJECT=$1 STATE=$2 CMD=$3
  timeout 3 node -e "
    try {
      const r = require('$HOME/mekong-cli/apps/openclaw-worker/lib/factory-roi-calculator');
      process.exit(r.shouldAvoidCommand('$PROJECT', '$STATE', '$(echo "$CMD" | head -c 60)') ? 0 : 1);
    } catch(e) { process.exit(1); }
  " 2>/dev/null
}

CYCLE_COUNT=0

while true; do
  CYCLE_COUNT=$((CYCLE_COUNT + 1))
  LOAD=$(sysctl -n vm.loadavg | awk '{print $2}')
  RAM=$(vm_stat | awk '/free/ {print $3}' | tr -d '.')
  echo "🧊 [$(date +%T)] Cycle=$CYCLE_COUNT Load=$LOAD RAM_free=$RAM"

  # Periodic zombie cleanup (every cycle)
  pkill -f "node.*jest" 2>/dev/null || true
  pkill -f "node.*vitest" 2>/dev/null || true
  pkill -f "tsserver.js" 2>/dev/null || true

  # PRIORITY QUEUE: Sort panes by project state
  # Projects with code (src/) get dispatched before empty projects
  SORTED_PANES=()
  for i in "${!PANES[@]}"; do
    STATE=$(detect_project_state "${PANE_DIRS[$i]}" 2>/dev/null || echo "empty")
    case "$STATE" in
      "deployed")       SORTED_PANES=("$i" "${SORTED_PANES[@]}") ;;  # highest priority
      "scaffolded")     SORTED_PANES=("$i" "${SORTED_PANES[@]}") ;;
      "needs_install")  SORTED_PANES=("$i" "${SORTED_PANES[@]}") ;;
      *)                SORTED_PANES+=("$i") ;;  # empty = lowest priority
    esac
  done

  for i in "${SORTED_PANES[@]}"; do
    PANE=${PANES[$i]}
    PROJECT=${PANE_PROJECTS[$i]}
    DIR=${PANE_DIRS[$i]}
    NAME=${PANE_NAMES[$i]}

    # HEALTH CHECK — verify pane is alive before anything else
    if ! check_pane_health "$PANE"; then
      echo "🔄 [P$PANE] Attempting respawn..."
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" -l "cd ~/mekong-cli && claude --dangerously-skip-permissions" 2>/dev/null || true
      sleep 0.5
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" Enter 2>/dev/null || true
      log_metric "respawn" "triggered" "0" "$PANE" "$PROJECT"
      continue
    fi

    # TIMEOUT CHECK — kill hung commands >10 min
    if ! check_command_timeout "$PANE" "$PROJECT"; then
      mark_dispatch_done "$PANE"
      continue
    fi

    PANE_OUTPUT=$(tmux capture-pane -t "$TMUX_SESSION:0.$PANE" -p 2>/dev/null || echo "")
    LAST_45=$(echo "$PANE_OUTPUT" | tail -n 45)
    LAST_5=$(echo "$PANE_OUTPUT" | tail -n 5)

    # CRASHED
    if echo "$LAST_5" | grep -qE "bash-5|% $"; then
      echo "☠️ [P$PANE] CRASHED — Restarting CC CLI..."
      log_metric "crash" "detected" "0" "$PANE" "$PROJECT"
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" -l "cd ~/mekong-cli && claude --dangerously-skip-permissions"
      sleep 0.5
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" Enter
      mark_dispatch_done "$PANE"
      continue
    fi

    # QUEUED
    if echo "$LAST_5" | grep -qE "Press up to edit queued"; then
      echo "📬 [P$PANE] QUEUED — Clearing..."
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" Escape
      sleep 1
      continue
    fi

    # WORKING — check LAST 5 lines ONLY (active animation near prompt)
    if echo "$LAST_5" | grep -qE "Bash\(|Read [0-9]|Write\(|Edit\(|Running|thinking|Hashing|Blanching|Creating|Hatching|Puttering|Generating|Tempering|Crunching|Bloviating|Actioning|Manifesting|Stewing|Billowing|Cogitated|Dilly-dallying|Infusing|Churned|Sautéed|Composting|Baked|Warping|Newspapering|Prestidigitating|Channeling|Metamorphosing|Propagating|Scampering|Brewing|Frosting|Moonwalking|Concocting|Sautéing|Orbiting|Compacting|Ebbing|Pondering|Crystallizing|Precipitating|Mulling|Searching for|thought for|Harmonizing"; then
      echo "⚙️ [P$PANE] WORKING on $PROJECT — SKIP"
      continue
    fi

    # JUST FINISHED — mark previous command as done, log success
    if echo "$LAST_5" | grep -qE "✅ Done|✔|Sautéed for|Brewed for|Baked for|Cogitated for|Crunched for"; then
      # Calculate duration and record learning outcome
      if [ -f "/tmp/cto_dispatch_ts_P${PANE}" ]; then
        DISPATCH_TS=$(cat "/tmp/cto_dispatch_ts_P${PANE}" 2>/dev/null || echo "0")
        DURATION=$(( $(date +%s) - DISPATCH_TS ))
        log_metric "command_complete" "success" "$DURATION" "$PANE" "$PROJECT"
        LAST_CMD=$(cat "/tmp/cto_last_cmd_P${PANE}" 2>/dev/null || echo "unknown")
        LAST_STATE=$(cat "/tmp/cto_last_state_P${PANE}" 2>/dev/null || echo "deployed")
        record_outcome "$PROJECT" "$LAST_STATE" "$LAST_CMD" "true" "$DURATION"
        mark_dispatch_done "$PANE"
      fi

      if echo "$LAST_5" | grep -qE "❯"; then
        : # idle — fall through to dispatch
      else
        echo "🏁 [P$PANE] JUST FINISHED — cooldown"
        continue
      fi
    fi

    # TRULY IDLE → dispatch command with cascade logic
    if echo "$LAST_5" | grep -qE "❯|bypass permissions"; then
      mark_dispatch_done "$PANE"  # Clear any stale dispatch timer

      COOLDOWN_FILE="/tmp/cto_cooldown_P${PANE}"
      NOW=$(date +%s)
      LAST_DISPATCH=$(cat "$COOLDOWN_FILE" 2>/dev/null || echo "0")
      ELAPSED=$((NOW - LAST_DISPATCH))

      if [ "$ELAPSED" -lt 180 ]; then
        echo "⏳ [P$PANE] COOLDOWN (${ELAPSED}s < 180s) — skip"
        continue
      fi

      # Save current output for chaining (A→B)
      save_pane_output "$PANE" "$LAST_45"

      # CASCADE LOGIC: analyze + get command
      CASCADE_CMD=$(get_cascade_command "$PANE" "$PROJECT" "$DIR" "$NAME" "$LAST_45" 2>/dev/null)

      # Save context file for CC CLI to reference
      echo "$LAST_45" | grep -v "^$" | grep -v "^─" | grep -v "bypass" | grep -v "qwen" | tail -15 > "/tmp/cto_context_P${PANE}.txt"

      # Determine layer
      LAYER="?"
      case "$CASCADE_CMD" in
        /raas*) LAYER="🏗️ Scaffold" ;;
        /studio*|/portfolio*) LAYER="🏯 Studio" ;;
        /founder*|/venture*) LAYER="👑 Founder" ;;
        /business*|/sales*|/marketing*) LAYER="💼 Business" ;;
        /plan*|/design*) LAYER="🎯 Product" ;;
        /cook*) LAYER="⚙️ Engineering" ;;
        *) LAYER="🏯 Studio" ;;
      esac

      echo "$LAYER [P$PANE] CASCADE DISPATCH for $PROJECT:"
      echo "   📌 $CASCADE_CMD"

      # DISPATCH + start timeout timer + save for learning
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" -l "$CASCADE_CMD"
      sleep 0.5
      tmux send-keys -t "$TMUX_SESSION:0.$PANE" Enter
      echo "$NOW" > "$COOLDOWN_FILE"
      mark_dispatch_start "$PANE"
      echo "$CASCADE_CMD" | head -c 60 > "/tmp/cto_last_cmd_P${PANE}"
      detect_project_state "$DIR" > "/tmp/cto_last_state_P${PANE}" 2>/dev/null || true
      log_metric "dispatch" "sent" "0" "$PANE" "$PROJECT" "$CASCADE_CMD"
      continue
    fi

    echo "❓ [P$PANE] UNKNOWN STATE"
    log_metric "unknown_state" "detected" "0" "$PANE" "$PROJECT"
  done

  echo "💤 [$(date +%T)] Sleeping ${SLEEP_INTERVAL}s..."
  sleep $SLEEP_INTERVAL
done
