import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/cli/index.ts'],
  format: ['esm'],
  dts: true,
  dtsConfig: false,
  external: [
    '@openclaw/solo-os',
    '@openclaw/solo-os/company-brain',
    '@openclaw/solo-os/daily-cycle',
    '@openclaw/solo-os/kpi-dashboard',
    '@openclaw/solo-os/automation-recipes',
    '@openclaw/solo-os/department-agents',
    '@openclaw/agencyos-dashboard',
    '@openclaw/agencyos-dashboard/api',
    '@openclaw/agencyos-dashboard/renderer',
    '@openclaw/cli-orchestrator',
    '@openclaw/cli-orchestrator/swarm',
    '@openclaw/vc-governance',
    '@openclaw/vc-governance/pitch-generator',
    '@openclaw/vc-governance/data-room',
    '@openclaw/vc-governance/iso-compliance',
    '@openclaw/vc-governance/exit-engine',
    '@openclaw/raas-marketplace',
    '@openclaw/raas-marketplace/catalog',
    '@openclaw/raas-marketplace/storefront',
    '@openclaw/raas-marketplace/sales-bot',
    '@openclaw/raas-marketplace/analytics',
    '@openclaw/agi-evolution',
    '@openclaw/agi-evolution/self-improver',
    '@openclaw/agi-evolution/version-tracker',
    '@openclaw/agi-evolution/benchmark',
    '@openclaw/agi-evolution/benchmark-runner',
    '@openclaw/cli-adapter',
    '@openclaw/cli-adapter/discovery',
    '@openclaw/engine/orchestration/auto-cto-pilot',
    '@openclaw/engine/raas/raas-api',
    '@openclaw/engine/raas/raas-onboarding',
    '@openclaw/engine/raas/raas-billing',
    '@openclaw/engine/raas/raas-health',
    '@openclaw/engine/raas/raas-rate-limiter',
    '@openclaw/engine/raas/raas-gateway',
    '@openclaw/engine/raas/raas-pricing',
  ],
});
