"""Tests for the AI Cell Runtime Engine (Phase 1).

Covers config loading and validation, privilege enforcement, output parsing,
and edge cases.  LLM calls are mocked to avoid requiring API keys.
"""

from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml  # type: ignore[import-untyped]

from src.mekong.cells.config import (
    find_cell_configs,
    load_cell_config,
    resolve_particle_config,
)
from src.mekong.cells.compliance import run_compliance_review
from src.mekong.cells.guardian import (
    DEFAULT_THRESHOLDS,
    Alert,
    HealthReport,
    load_guardian_thresholds,
    run_guardian_review,
)
from src.mekong.graph.store import open_db
from src.mekong.cells.runner import _parse_recommendation, run_cell, run_compliance
from src.mekong.cells.strategist import (
    build_strategist_prompt,
    parse_strategist_output,
)
from src.mekong.cells.types import (
    CellBoundaries,
    CellConfig,
    CellPrivileges,
    CellRecommendation,
    ComplianceResult,
)
from src.mekong.constitution import parse_constitution

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def valid_yaml() -> str:
    """Return a minimal valid cell YAML string."""
    return yaml.dump({
        "role": "strategist",
        "model": "anthropic/claude-sonnet-4",
        "capabilities": ["analysis", "recommendation"],
        "privileges": {"max_budget": 100.0, "requires_approval": False},
        "boundaries": {"read": ["particle/*"], "write": ["particle/reports/*"]},
    })


@pytest.fixture
def valid_config() -> CellConfig:
    """Return a ``CellConfig`` instance suitable for testing ``run_cell``."""
    return CellConfig(
        role="strategist",
        model="anthropic/claude-sonnet-4",
        capabilities=["analysis", "recommendation"],
        privileges=CellPrivileges(max_budget=100.0, requires_approval=False),
        boundaries=CellBoundaries(
            read=["particle/*"],
            write=["particle/reports/*"],
        ),
    )


@pytest.fixture
def disabled_config() -> CellConfig:
    """Return a config with exhausted budget."""
    return CellConfig(
        role="disabled-cell",
        model="anthropic/claude-sonnet-4",
        capabilities=[],
        privileges=CellPrivileges(max_budget=0.0, requires_approval=False),
        boundaries=CellBoundaries(),
    )


@pytest.fixture
def temp_particle(tmp_path: Path) -> Path:
    """Create a minimal particle directory with a ZENOS.md constitution."""
    particle_dir = tmp_path / "test-particle"
    particle_dir.mkdir(parents=True)

    constitution = """# ZENOS.md — Test Particle

## Article 1: Mission Integrity — Test and learn

The particle exists to serve testing.

## Article 2: Right to Exit

Any participant may exit at any time.

## Article 3: Anti-Concentration

No single actor may hold more than 25% voting power.
"""
    (particle_dir / "ZENOS.md").write_text(constitution, encoding="utf-8")
    return particle_dir


@pytest.fixture
def rich_particle(tmp_path: Path) -> Path:
    """Create a particle with a full constitution covering all compliance axes.

    Includes Mission, AI Boundaries, Behavioral Integrity/Anti-Concentration,
    and Right to Exit articles.
    """
    particle_dir = tmp_path / "rich-particle"
    particle_dir.mkdir(parents=True)

    constitution = """# ZENOS.md — Rich Particle

## Article 1: Mission Integrity

This particle exists to serve testing and learning. All operations
shall be evaluated against this mission.

## Article 2: Governance

Major decisions are made through community voting with each member
holding one vote. Day-to-day operations are delegated to an elected
steering committee.

## Article 3: AI Cell Boundaries

AI Cells operate within defined privilege limits. Cells may not
escalate their own privileges, access data outside their scope,
or act without human approval for high-impact decisions.

## Article 4: Economics

Value generated by the particle is distributed proportionally
based on member contributions as measured by transparent metrics.

## Article 5: Right to Exit

Any participant may exit at any time, taking their data and a fair
share of accrued common value. No exit penalty shall be imposed.

## Article 6: Behavioral Integrity

The particle shall resist anti-concentration patterns. No single
actor may consolidate decision-making authority. Checks and balances
shall be maintained.

## Article 7: Evolution

This constitution may be amended by super-majority consensus
through a transparent proposal process.

## Article 8: Anti-Capture

The particle shall resist capture by any single agent or faction.
Governance authority is distributed across roles with defined
boundaries.
"""
    (particle_dir / "ZENOS.md").write_text(constitution, encoding="utf-8")
    return particle_dir


# ---------------------------------------------------------------------------
# Config loading tests
# ---------------------------------------------------------------------------


class TestLoadConfig:
    def test_load_config_valid(self, valid_yaml: str, tmp_path: Path) -> None:
        """A valid YAML file loads into a ``CellConfig`` with correct fields."""
        config_path = tmp_path / "cell.yaml"
        config_path.write_text(valid_yaml, encoding="utf-8")

        config = load_cell_config(config_path)

        assert config.role == "strategist"
        assert config.model == "anthropic/claude-sonnet-4"
        assert config.capabilities == ["analysis", "recommendation"]
        assert config.privileges.max_budget == 100.0
        assert config.privileges.requires_approval is False
        assert config.boundaries.read == ["particle/*"]
        assert config.boundaries.write == ["particle/reports/*"]

    def test_load_config_missing_field(self, tmp_path: Path) -> None:
        """YAML missing ``model`` raises ``ValueError``."""
        data = {"role": "strategist"}  # missing model
        config_path = tmp_path / "missing.yaml"
        config_path.write_text(yaml.dump(data), encoding="utf-8")

        with pytest.raises(ValueError, match="missing required field"):
            load_cell_config(config_path)

    def test_load_config_missing_required_both(self, tmp_path: Path) -> None:
        """YAML missing both required fields raises ``ValueError``."""
        config_path = tmp_path / "empty.yaml"
        config_path.write_text(yaml.dump({"capabilities": []}), encoding="utf-8")

        with pytest.raises(ValueError, match="model.*role|role.*model"):
            load_cell_config(config_path)

    def test_load_config_nonexistent(self) -> None:
        """Loading a non-existent file raises ``FileNotFoundError``."""
        with pytest.raises(FileNotFoundError):
            load_cell_config("/nonexistent/path/cell.yaml")

    def test_load_config_invalid_yaml(self, tmp_path: Path) -> None:
        """Malformed YAML raises ``ValueError``."""
        config_path = tmp_path / "bad.yaml"
        config_path.write_text(": : invalid yaml [[[", encoding="utf-8")

        with pytest.raises(ValueError, match="Invalid YAML"):
            load_cell_config(config_path)

    def test_load_config_not_a_mapping(self, tmp_path: Path) -> None:
        """YAML that is not a dict raises ``ValueError``."""
        config_path = tmp_path / "scalar.yaml"
        config_path.write_text(yaml.dump("just a string"), encoding="utf-8")

        with pytest.raises(ValueError, match="must be a YAML mapping"):
            load_cell_config(config_path)

    def test_load_config_minimal(self, tmp_path: Path) -> None:
        """Minimal valid config (only required fields) loads without error."""
        data = {"role": "observer", "model": "gpt-4o-mini"}
        config_path = tmp_path / "minimal.yaml"
        config_path.write_text(yaml.dump(data), encoding="utf-8")

        config = load_cell_config(config_path)
        assert config.role == "observer"
        assert config.model == "gpt-4o-mini"
        assert config.capabilities == []
        assert config.privileges.max_budget == 0.0
        assert config.privileges.requires_approval is False


# ---------------------------------------------------------------------------
# Particle resolution tests
# ---------------------------------------------------------------------------


class TestResolveParticle:
    def test_resolve_by_path(self, temp_particle: Path) -> None:
        """Resolving by existing directory path works."""
        resolved = resolve_particle_config(str(temp_particle))
        assert resolved == temp_particle.resolve()

    def test_resolve_nonexistent_raises(self) -> None:
        """Resolving a non-existent particle raises ``FileNotFoundError``."""
        with pytest.raises(FileNotFoundError, match="Particle not found"):
            resolve_particle_config("__nonexistent_particle_xyz__")


# ---------------------------------------------------------------------------
# Cell config enumeration tests
# ---------------------------------------------------------------------------


class TestFindCellConfigs:
    def test_find_cell_configs(self, tmp_path: Path) -> None:
        """Enumerate cell YAML files in a particle's ``cells/`` subdirectory."""
        particle_dir = tmp_path / "particle"
        cells_dir = particle_dir / "cells"
        cells_dir.mkdir(parents=True)

        (cells_dir / "strategist.yaml").write_text(yaml.dump({
            "role": "strategist", "model": "claude-sonnet-4",
        }), encoding="utf-8")
        (cells_dir / "compliance.yaml").write_text(yaml.dump({
            "role": "compliance", "model": "claude-haiku-4-5",
        }), encoding="utf-8")

        configs = find_cell_configs(particle_dir)
        assert len(configs) == 2
        assert configs[0]["role"] == "compliance"  # sorted
        assert configs[1]["role"] == "strategist"
        assert "_path" in configs[0]

    def test_find_cell_configs_no_cells_dir(self, tmp_path: Path) -> None:
        """Particle without ``cells/`` returns empty list."""
        particle_dir = tmp_path / "empty-particle"
        particle_dir.mkdir()
        assert find_cell_configs(particle_dir) == []

    def test_find_cell_configs_invalid_yaml_skipped(self, tmp_path: Path) -> None:
        """Invalid YAML files in ``cells/`` are silently skipped."""
        particle_dir = tmp_path / "particle"
        cells_dir = particle_dir / "cells"
        cells_dir.mkdir(parents=True)

        (cells_dir / "good.yaml").write_text(yaml.dump({
            "role": "scout", "model": "gpt-4o",
        }), encoding="utf-8")
        # Unclosed bracket causes a YAML scanner error
        (cells_dir / "bad.yaml").write_text("unmatched: [bracket", encoding="utf-8")

        configs = find_cell_configs(particle_dir)
        assert len(configs) == 1
        assert configs[0]["role"] == "scout"


# ---------------------------------------------------------------------------
# Output parsing tests
# ---------------------------------------------------------------------------


class TestParseRecommendation:
    def test_parse_valid_output(self) -> None:
        """A complete valid dict converts to ``CellRecommendation``."""
        raw = {
            "recommendation": "Increase marketing budget by 15%",
            "confidence": 0.85,
            "rationale": "ROI analysis shows diminishing returns at current spend",
            "risk_factors": ["Budget overrun", "Channel saturation"],
            "estimated_impact": "high",
        }
        result = _parse_recommendation(raw)
        assert isinstance(result, CellRecommendation)
        assert result.recommendation == "Increase marketing budget by 15%"
        assert result.confidence == 0.85
        assert "Budget overrun" in result.risk_factors
        assert result.estimated_impact == "high"

    def test_parse_missing_fields_default(self) -> None:
        """Missing fields default to empty / safe values."""
        raw: dict = {}
        result = _parse_recommendation(raw)
        assert result.recommendation == ""
        assert result.confidence == 0.0
        assert result.rationale == ""
        assert result.risk_factors == []
        assert result.estimated_impact == "medium"

    def test_parse_bad_impact_defaults_to_medium(self) -> None:
        """Invalid ``estimated_impact`` defaults to ``"medium"``."""
        raw = {"estimated_impact": "extreme"}
        result = _parse_recommendation(raw)
        assert result.estimated_impact == "medium"

    def test_parse_partial_fields(self) -> None:
        """Partial input only fills the provided fields."""
        raw = {"recommendation": "Do nothing", "confidence": 0.3}
        result = _parse_recommendation(raw)
        assert result.recommendation == "Do nothing"
        assert result.confidence == 0.3
        assert result.rationale == ""
        assert result.risk_factors == []


# ---------------------------------------------------------------------------
# Privilege enforcement tests
# ---------------------------------------------------------------------------


class TestPrivilegeEnforcement:
    def test_max_budget_zero_raises(self, disabled_config: CellConfig) -> None:
        """``run_cell`` raises immediately when ``max_budget <= 0``."""
        with pytest.raises(ValueError, match="budget exhausted"):
            run_cell(disabled_config, "/tmp", "test prompt")

    def test_max_budget_negative_raises(self) -> None:
        """Negative budget is also treated as exhausted."""
        config = CellConfig(
            role="over-budget",
            model="claude-sonnet-4",
            capabilities=[],
            privileges=CellPrivileges(max_budget=-1.0),
            boundaries=CellBoundaries(),
        )
        with pytest.raises(ValueError, match="budget exhausted"):
            run_cell(config, "/tmp", "test prompt")


# ---------------------------------------------------------------------------
# run_cell integration test (mocked LLM)
# ---------------------------------------------------------------------------


class TestRunCell:
    def test_run_cell_success(
        self,
        valid_config: CellConfig,
        temp_particle: Path,
    ) -> None:
        """``run_cell`` with valid inputs returns a ``CellRecommendation``."""
        mock_response = {
            "choices": [{
                "message": {
                    "content": json.dumps({
                        "recommendation": "Run more tests",
                        "confidence": 0.9,
                        "rationale": "Testing reduces risk",
                        "risk_factors": ["Time cost"],
                        "estimated_impact": "medium",
                    }),
                },
            }],
        }

        with patch.dict(os.environ, {"OPENROUTER_API_KEY": "test-key"}, clear=False):
            with patch("requests.post") as mock_post:
                mock_post.return_value.status_code = 200
                mock_post.return_value.json.return_value = mock_response

                result = run_cell(
                    valid_config,
                    str(temp_particle),
                    "What should we do?",
                    db_path=":memory:",
                )

        assert isinstance(result, CellRecommendation)
        assert result.recommendation == "Run more tests"
        assert result.confidence == 0.9
        assert "Time cost" in result.risk_factors


# ---------------------------------------------------------------------------
# Compliance check tests
# ---------------------------------------------------------------------------


class TestRunCompliance:
    def test_compliance_pass(
        self,
        valid_config: CellConfig,
        temp_particle: Path,
    ) -> None:
        """``run_compliance`` returns ``ComplianceResult`` with checked articles."""
        recommendation = CellRecommendation(
            recommendation="Proceed with plan",
            confidence=0.8,
            rationale="Solid analysis",
            risk_factors=[],
            estimated_impact="low",
        )

        with patch("src.mekong.cells.runner.record_behavior") as mock_record:
            result = run_compliance(
                valid_config,
                str(temp_particle),
                recommendation,
                db_path=":memory:",
            )

        assert isinstance(result, ComplianceResult)
        assert result.verdict in ("PASS", "WARNING", "VIOLATION")
        assert len(result.checked_articles) >= 3  # our fixture has 3 articles
        mock_record.assert_called_once()

    def test_compliance_empty_recommendation_passes(
        self,
        valid_config: CellConfig,
        temp_particle: Path,
    ) -> None:
        """Empty recommendation yields PASS — nothing to violate."""
        recommendation = CellRecommendation(
            recommendation="",
            confidence=0.0,
            rationale="",
            risk_factors=[],
            estimated_impact="low",
        )

        with patch("src.mekong.cells.runner.record_behavior"):
            result = run_compliance(
                valid_config,
                str(temp_particle),
                recommendation,
            )

        assert result.verdict == "PASS"


# ---------------------------------------------------------------------------
# Compliance review cell tests
# ---------------------------------------------------------------------------


class TestComplianceReview:
    """Tests for the compliance cell's article-by-article review."""

    def test_compliance_review_pass(self, rich_particle: Path) -> None:
        """Clean mission-aligned recommendation returns PASS."""
        rec = CellRecommendation(
            recommendation="Increase testing coverage by adding more unit tests",
            confidence=0.85,
            rationale="Testing reduces risk",
            risk_factors=["Time cost"],
            estimated_impact="medium",
        )

        result = run_compliance_review(
            particle_id="rich-particle",
            recommendation=rec,
            constitution_path=str(rich_particle / "ZENOS.md"),
        )

        assert result.verdict == "PASS"
        assert len(result.checked_articles) >= 7
        assert result.violations == []
        assert result.warnings == []

    def test_compliance_mission_violation(self, rich_particle: Path) -> None:
        """Recommendation that contradicts mission returns VIOLATION."""
        rec = CellRecommendation(
            recommendation="Abandon the mission and pivot to something more profitable",
            confidence=0.3,
            rationale="Financial pressures require change",
            risk_factors=["Loss of identity"],
            estimated_impact="high",
        )

        result = run_compliance_review(
            particle_id="rich-particle",
            recommendation=rec,
            constitution_path=str(rich_particle / "ZENOS.md"),
        )

        assert result.verdict == "VIOLATION"
        # Should contain a mission-related violation
        assert any("Mission" in v or "mission" in v for v in result.violations)
        assert any("Article 1" in v for v in result.violations)

    def test_compliance_boundary_violation(self, rich_particle: Path) -> None:
        """Recommendation that exceeds AI Cell boundaries returns VIOLATION."""
        rec = CellRecommendation(
            recommendation="Escalate privileges to gain unrestricted access to all company data without approval",
            confidence=0.6,
            rationale="Need full access for efficiency",
            risk_factors=["Security risk"],
            estimated_impact="high",
        )

        result = run_compliance_review(
            particle_id="rich-particle",
            recommendation=rec,
            constitution_path=str(rich_particle / "ZENOS.md"),
        )

        assert result.verdict == "VIOLATION"
        assert any("boundar" in v or "Boundar" in v for v in result.violations)
        assert any("Article 3" in v for v in result.violations)

    def test_compliance_exit_violation(self, rich_particle: Path) -> None:
        """Recommendation that restricts exit returns VIOLATION."""
        rec = CellRecommendation(
            recommendation="Block exit for key members to prevent knowledge loss and lock them in",
            confidence=0.4,
            rationale="Protect intellectual property",
            risk_factors=["Legal risk"],
            estimated_impact="high",
        )

        result = run_compliance_review(
            particle_id="rich-particle",
            recommendation=rec,
            constitution_path=str(rich_particle / "ZENOS.md"),
        )

        assert result.verdict == "VIOLATION"
        assert any("exit" in v.lower() for v in result.violations)
        assert any("Article 5" in v for v in result.violations)

    def test_compliance_empty_recommendation(self, rich_particle: Path) -> None:
        """Empty recommendation yields PASS — no content to violate."""
        rec = CellRecommendation(
            recommendation="",
            confidence=0.0,
            rationale="",
            risk_factors=[],
            estimated_impact="low",
        )

        result = run_compliance_review(
            particle_id="rich-particle",
            recommendation=rec,
            constitution_path=str(rich_particle / "ZENOS.md"),
        )

        assert result.verdict == "PASS"
        assert result.violations == []

    def test_compliance_missing_constitution(self, tmp_path: Path) -> None:
        """Missing constitution file raises FileNotFoundError."""
        rec = CellRecommendation(
            recommendation="Do something",
            confidence=0.5,
            rationale="Because",
            risk_factors=[],
            estimated_impact="low",
        )

        with pytest.raises(FileNotFoundError, match="Constitution not found"):
            run_compliance_review(
                particle_id="missing",
                recommendation=rec,
                constitution_path=str(tmp_path / "nonexistent" / "ZENOS.md"),
            )


# ---------------------------------------------------------------------------
# Compliance graph recording tests
# ---------------------------------------------------------------------------


class TestComplianceGraphRecording:
    def test_runner_records_review(self, valid_config: CellConfig, tmp_path: Path) -> None:
        """``run_compliance`` records the review to the behavior graph."""
        from unittest.mock import patch as _patch

        particle_dir = tmp_path / "test-recording"
        particle_dir.mkdir(parents=True)
        constitution = """# Recording Test

## Article 1: Mission

Test mission.

## Article 2: Right to Exit

Free to leave.

## Article 3: Anti-Concentration

No single point of control.
"""
        (particle_dir / "ZENOS.md").write_text(constitution, encoding="utf-8")

        recommendation = CellRecommendation(
            recommendation="Proceed with plan",
            confidence=0.8,
            rationale="Good reasons",
            risk_factors=[],
            estimated_impact="low",
        )

        with _patch("src.mekong.cells.runner.record_behavior") as mock_record:
            result = run_compliance(
                valid_config,
                str(particle_dir),
                recommendation,
                db_path=":memory:",
            )

        assert isinstance(result, ComplianceResult)
        mock_record.assert_called_once()
        call_kwargs = mock_record.call_args.kwargs
        assert call_kwargs["action"] == "constitutional_review"
        assert "cell:" in call_kwargs["source_id"]
        assert call_kwargs["payload"]["verdict"] == "PASS"


# ---------------------------------------------------------------------------
# Edge case tests
# ---------------------------------------------------------------------------


class TestEdgeCases:
    def test_empty_cells_dir(self, tmp_path: Path) -> None:
        """Empty ``cells/`` directory returns empty list."""
        particle_dir = tmp_path / "no-cells"
        particle_dir.mkdir()
        (particle_dir / "cells").mkdir()

        assert find_cell_configs(particle_dir) == []

    def test_particle_without_cells_dir(self, tmp_path: Path) -> None:
        """Particle without ``cells/`` dir returns empty list."""
        particle_dir = tmp_path / "bare"
        particle_dir.mkdir()

        # Also create ZENOS.md so it looks like a valid particle
        (particle_dir / "ZENOS.md").write_text("# Bare\n\n## Article 1: Nothing\n\nNothing.", encoding="utf-8")

        assert find_cell_configs(particle_dir) == []

    def test_parse_recommendation_none_impact(self) -> None:
        """None impact defaults to medium."""
        raw = {"estimated_impact": None}
        result = _parse_recommendation(raw)
        assert result.estimated_impact == "medium"

    def test_disabled_config_with_approval(self) -> None:
        """Disabled cell with ``requires_approval=True`` still fails budget check."""
        config = CellConfig(
            role="needs-approval",
            model="claude-sonnet-4",
            capabilities=[],
            privileges=CellPrivileges(max_budget=0.0, requires_approval=True),
            boundaries=CellBoundaries(),
        )
        with pytest.raises(ValueError, match="budget exhausted"):
            run_cell(config, "/tmp", "prompt")


# ---------------------------------------------------------------------------
# Strategist cell tests
# ---------------------------------------------------------------------------


class TestStrategistPromptBuilding:
    def test_prompt_contains_mission(self, temp_particle: Path) -> None:
        """The system prompt includes the mission statement from the constitution."""
        constitution = parse_constitution(str(temp_particle / "ZENOS.md"))
        system_prompt, user_prompt = build_strategist_prompt(
            particle="test-particle",
            constitution=constitution,
            question="Should we expand?",
        )
        assert "Mission Integrity" in system_prompt or "serve testing" in system_prompt

    def test_prompt_contains_role(self, temp_particle: Path) -> None:
        """The system prompt identifies the strategist role."""
        constitution = parse_constitution(str(temp_particle / "ZENOS.md"))
        system_prompt, _ = build_strategist_prompt(
            particle="test-particle",
            constitution=constitution,
            question="Should we expand?",
        )
        assert "Strategist" in system_prompt

    def test_user_prompt_contains_question(self, temp_particle: Path) -> None:
        """The user prompt includes the strategic question."""
        constitution = parse_constitution(str(temp_particle / "ZENOS.md"))
        _, user_prompt = build_strategist_prompt(
            particle="test-particle",
            constitution=constitution,
            question="Should we expand?",
        )
        assert "Should we expand?" in user_prompt

    def test_user_prompt_contains_articles(self, temp_particle: Path) -> None:
        """The user prompt lists constitution articles."""
        constitution = parse_constitution(str(temp_particle / "ZENOS.md"))
        _, user_prompt = build_strategist_prompt(
            particle="test-particle",
            constitution=constitution,
            question="Should we expand?",
        )
        assert "Article 1" in user_prompt
        assert "Article 2" in user_prompt


class TestParseStrategistOutput:
    def test_parse_valid_output(self) -> None:
        """Valid JSON produces a ``CellRecommendation`` with correct fields."""
        raw = json.dumps({
            "recommendation": "Expand marketing by 20%",
            "confidence": 0.85,
            "rationale": "Strong ROI potential based on historical data",
            "risk_factors": ["Budget overrun", "Channel saturation"],
            "estimated_impact": "high",
        })
        result = parse_strategist_output(raw)
        assert isinstance(result, CellRecommendation)
        assert result.recommendation == "Expand marketing by 20%"
        assert result.confidence == 0.85
        assert "Budget overrun" in result.risk_factors
        assert result.estimated_impact == "high"

    def test_parse_valid_output_with_code_fences(self) -> None:
        """JSON wrapped in markdown code fences is handled correctly."""
        raw = "```json\n{\"recommendation\": \"Test\", \"confidence\": 0.5, \"rationale\": \"Reasoning\"}\n```"
        result = parse_strategist_output(raw)
        assert result.recommendation == "Test"
        assert result.confidence == 0.5

    def test_parse_missing_recommendation_raises(self) -> None:
        """Missing 'recommendation' raises ValueError."""
        raw = json.dumps({"confidence": 0.8, "rationale": "Good reasons"})
        with pytest.raises(ValueError, match="recommendation"):
            parse_strategist_output(raw)

    def test_parse_missing_confidence_raises(self) -> None:
        """Missing 'confidence' raises ValueError."""
        raw = json.dumps({"recommendation": "Do it", "rationale": "Why not"})
        with pytest.raises(ValueError, match="confidence"):
            parse_strategist_output(raw)

    def test_parse_confidence_out_of_range_raises(self) -> None:
        """Confidence outside 0-1 raises ValueError."""
        raw = json.dumps({
            "recommendation": "Do it",
            "confidence": 1.5,
            "rationale": "Reasoning",
        })
        with pytest.raises(ValueError, match="confidence"):
            parse_strategist_output(raw)

    def test_parse_negative_confidence_raises(self) -> None:
        """Negative confidence raises ValueError."""
        raw = json.dumps({
            "recommendation": "Do it",
            "confidence": -0.1,
            "rationale": "Reasoning",
        })
        with pytest.raises(ValueError, match="confidence"):
            parse_strategist_output(raw)

    def test_parse_missing_rationale_raises(self) -> None:
        """Missing 'rationale' raises ValueError."""
        raw = json.dumps({"recommendation": "Do it", "confidence": 0.7})
        with pytest.raises(ValueError, match="rationale"):
            parse_strategist_output(raw)

    def test_parse_empty_rationale_raises(self) -> None:
        """Empty rationale string raises ValueError."""
        raw = json.dumps({
            "recommendation": "Do it",
            "confidence": 0.7,
            "rationale": "",
        })
        with pytest.raises(ValueError, match="rationale"):
            parse_strategist_output(raw)

    def test_parse_invalid_json_raises(self) -> None:
        """Non-JSON input raises ValueError."""
        with pytest.raises(ValueError, match="not valid JSON"):
            parse_strategist_output("not json at all")

    def test_empty_input_raises(self) -> None:
        """Empty input raises ValueError."""
        with pytest.raises(ValueError, match="empty"):
            parse_strategist_output("")

    def test_parse_partial_fields(self) -> None:
        """Partial valid input accepts only provided fields."""
        raw = json.dumps({
            "recommendation": "Wait",
            "confidence": 0.3,
            "rationale": "Not enough data",
        })
        result = parse_strategist_output(raw)
        assert result.recommendation == "Wait"
        assert result.confidence == 0.3
        assert result.rationale == "Not enough data"
        assert result.risk_factors == []
        assert result.estimated_impact == "medium"

    def test_parse_invalid_impact_defaults_medium(self) -> None:
        """Invalid impact falls back to 'medium'."""
        raw = json.dumps({
            "recommendation": "Do it",
            "confidence": 0.5,
            "rationale": "Reasonable",
            "estimated_impact": "extreme",
        })
        result = parse_strategist_output(raw)
        assert result.estimated_impact == "medium"


class TestStrategistGraphRecording:
    def test_strategist_graph_recording(
        self,
        valid_config: CellConfig,
        temp_particle: Path,
    ) -> None:
        """``run_strategist`` records a behavior graph entry."""
        from src.mekong.cells.runner import run_strategist

        mock_response = {
            "choices": [{
                "message": {
                    "content": json.dumps({
                        "recommendation": "Expand to new markets",
                        "confidence": 0.75,
                        "rationale": "Market analysis supports moderate expansion",
                        "risk_factors": ["Capital requirements"],
                        "estimated_impact": "high",
                    }),
                },
            }],
        }

        with patch.dict(os.environ, {"OPENROUTER_API_KEY": "test-key"}, clear=False):
            with patch("requests.post") as mock_post:
                mock_post.return_value.status_code = 200
                mock_post.return_value.json.return_value = mock_response

                with patch("src.mekong.cells.runner.record_behavior") as mock_record:
                    result = run_strategist(
                        valid_config,
                        str(temp_particle),
                        "Should we expand?",
                        db_path=":memory:",
                    )

        assert isinstance(result, CellRecommendation)
        assert result.recommendation == "Expand to new markets"
        assert result.confidence == 0.75
        mock_record.assert_called_once()
        call_kwargs = mock_record.call_args.kwargs
        assert call_kwargs["action"] == "strategist_recommendation"
        assert call_kwargs["source_id"] == "cell:strategist"
        assert "test-particle" in call_kwargs["target_id"]


class TestRunStrategist:
    def test_run_strategist_budget_exhausted(
        self,
        disabled_config: CellConfig,
    ) -> None:
        """``run_strategist`` raises when budget is exhausted."""
        from src.mekong.cells.runner import run_strategist

        with pytest.raises(ValueError, match="budget exhausted"):
            run_strategist(disabled_config, "/tmp", "Should we expand?")

    def test_run_strategist_missing_particle(self, valid_config: CellConfig) -> None:
        """``run_strategist`` raises when particle ZENOS.md is missing."""
        from src.mekong.cells.runner import run_strategist

        fake_dir = Path("/nonexistent/particle")
        with pytest.raises(FileNotFoundError, match="Constitution not found"):
            run_strategist(valid_config, str(fake_dir), "Should we expand?")


# ---------------------------------------------------------------------------
# Strategist + Compliance integration tests
# ---------------------------------------------------------------------------


class TestRunStrategistWithCompliance:
    """Tests for the combined strategist + compliance execution."""

    @pytest.fixture
    def strategist_particle(self, tmp_path: Path) -> Path:
        """Create a particle with a strategist cell config and constitution."""
        particle_dir = tmp_path / "strategist-test"
        particle_dir.mkdir(parents=True)

        # Write constitution
        constitution = """# ZENOS.md — Strategist Test

## Article 1: Mission Integrity

The particle exists to serve testing and learning. All operations
shall be evaluated against this mission.

## Article 2: Governance

Major decisions are made through community voting.

## Article 3: AI Cell Boundaries

AI Cells operate within defined privilege limits and may not
escalate their own privileges without approval.

## Article 4: Right to Exit

Any participant may exit at any time with no penalty.

## Article 5: Behavioral Integrity

The particle shall resist anti-concentration patterns.
"""
        (particle_dir / "ZENOS.md").write_text(constitution, encoding="utf-8")

        # Write strategist cell config
        cells_dir = particle_dir / "cells"
        cells_dir.mkdir(parents=True)
        config_yaml = yaml.dump({
            "role": "strategist",
            "model": "anthropic/claude-sonnet-4",
            "capabilities": ["analysis", "recommendation"],
            "privileges": {"max_budget": 100.0, "requires_approval": False},
            "boundaries": {"read": ["particle/*"], "write": ["particle/reports/*"]},
        })
        (cells_dir / "strategist.yaml").write_text(config_yaml, encoding="utf-8")

        return particle_dir

    def test_auto_compliance_has_both_sections(
        self,
        strategist_particle: Path,
    ) -> None:
        """Merged result contains both strategist recommendation and compliance sections."""
        from src.mekong.cells.runner import run_strategist_with_compliance

        mock_response = {
            "choices": [{
                "message": {
                    "content": json.dumps({
                        "recommendation": "Market analysis shows growth opportunity",
                        "confidence": 0.85,
                        "rationale": "Strong market indicators support expansion",
                        "risk_factors": ["Competition", "Capital requirements"],
                        "estimated_impact": "high",
                    }),
                },
            }],
        }

        with patch.dict(os.environ, {"OPENROUTER_API_KEY": "test-key"}, clear=False):
            with patch("requests.post") as mock_post:
                mock_post.return_value.status_code = 200
                mock_post.return_value.json.return_value = mock_response

                with patch("src.mekong.cells.runner.record_behavior"):
                    result = run_strategist_with_compliance(
                        particle_id=str(strategist_particle),
                        prompt="Analyze the market",
                        db_path=":memory:",
                    )

        assert isinstance(result, dict)
        assert "recommendation" in result
        assert "compliance" in result
        assert "behavior_graph" in result

        # Recommendation section
        rec = result["recommendation"]
        assert rec["recommendation"] == "Market analysis shows growth opportunity"
        assert rec["confidence"] == 0.85
        assert rec["estimated_impact"] == "high"
        assert "Competition" in rec["risk_factors"]

        # Compliance section
        comp = result["compliance"]
        assert comp["verdict"] in ("PASS", "WARNING", "VIOLATION")
        assert isinstance(comp["checked_articles"], list)
        assert len(comp["checked_articles"]) >= 4
        assert isinstance(comp["violations"], list)
        assert isinstance(comp["warnings"], list)

        # Behavior graph — two entries
        bg = result["behavior_graph"]
        assert len(bg) == 2

    def test_behavior_graph_entries(
        self,
        strategist_particle: Path,
    ) -> None:
        """Both strategist and compliance entries exist in the behavior graph list."""
        from src.mekong.cells.runner import run_strategist_with_compliance

        mock_response = {
            "choices": [{
                "message": {
                    "content": json.dumps({
                        "recommendation": "Expand to new markets cautiously",
                        "confidence": 0.75,
                        "rationale": "Market analysis supports moderate expansion with controlled risk",
                        "risk_factors": ["Capital requirements"],
                        "estimated_impact": "medium",
                    }),
                },
            }],
        }

        with patch.dict(os.environ, {"OPENROUTER_API_KEY": "test-key"}, clear=False):
            with patch("requests.post") as mock_post:
                mock_post.return_value.status_code = 200
                mock_post.return_value.json.return_value = mock_response

                with patch("src.mekong.cells.runner.record_behavior"):
                    result = run_strategist_with_compliance(
                        particle_id=str(strategist_particle),
                        prompt="Should we expand?",
                        db_path=":memory:",
                    )

        bg = result["behavior_graph"]

        # First entry: strategist recommendation
        assert bg[0]["action"] == "strategist_recommendation"
        assert "source_id" in bg[0]
        assert "target_id" in bg[0]
        assert bg[0]["value"] == 0.75
        assert "strategist" in bg[0]["source_id"]

        # Second entry: constitutional review
        assert bg[1]["action"] == "constitutional_review"
        assert "source_id" in bg[1]
        assert "target_id" in bg[1]
        assert bg[1]["value"] == 0.0

        # Both entries target the same particle
        assert bg[0]["target_id"] == bg[1]["target_id"]

    def test_auto_compliance_missing_config(
        self,
        tmp_path: Path,
    ) -> None:
        """Missing strategist config raises FileNotFoundError."""
        from src.mekong.cells.runner import run_strategist_with_compliance

        # Create particle with ZENOS.md but no cells directory
        particle_dir = tmp_path / "incomplete-particle"
        particle_dir.mkdir(parents=True)
        (particle_dir / "ZENOS.md").write_text("# Incomplete\n\n## Article 1: Mission\n\nTest.", encoding="utf-8")

        with pytest.raises(FileNotFoundError, match="Strategist cell config not found"):
            run_strategist_with_compliance(
                particle_id=str(particle_dir),
                prompt="Analyze",
                db_path=":memory:",
            )


# ---------------------------------------------------------------------------
# Guardian Cell tests
# ---------------------------------------------------------------------------


class TestGuardianCell:
    """Guardian Cell health review and threshold tests."""

    # ----- helpers -----

    @staticmethod
    def _graph_db(tmp_path: Path) -> str:
        """Create a temporary graph DB with schema, return its path."""
        db_path = str(tmp_path / "guardian.db")
        conn = open_db(db_path)
        conn.close()
        return db_path

    @staticmethod
    def _ensure(conn: sqlite3.Connection, entity_id: str) -> None:
        """Ensure an entity exists in the graph database (ignore if present)."""
        conn.execute(
            "INSERT OR IGNORE INTO entities (id, name, kind) VALUES (?, ?, ?)",
            (entity_id, entity_id, "particle"),
        )

    @staticmethod
    def _insert_behavior(
        conn: sqlite3.Connection,
        source_id: str,
        target_id: str,
        action: str = "test_action",
        review: str = "not_reviewed",
    ) -> None:
        """Insert a behavior edge with explicit constitutional_review status."""
        TestGuardianCell._ensure(conn, source_id)
        TestGuardianCell._ensure(conn, target_id)
        conn.execute(
            """INSERT INTO behaviors
                   (source_id, target_id, action, constitutional_review, timestamp)
               VALUES (?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))""",
            (source_id, target_id, action, review),
        )

    # ----- threshold loader test -----

    def test_load_guardian_thresholds(self) -> None:
        """``load_guardian_thresholds`` returns a fresh copy of defaults."""
        thresholds = load_guardian_thresholds("particle:test")
        assert thresholds == DEFAULT_THRESHOLDS
        assert thresholds is not DEFAULT_THRESHOLDS  # must be a copy, not the same dict

    # ----- health review tests -----

    def test_guardian_clean(self, tmp_path: Path) -> None:
        """No violations returns GREEN with zero alerts."""
        db = self._graph_db(tmp_path)
        conn = open_db(db)
        for i in range(10):
            self._insert_behavior(conn, "particle:alpha", f"entity:pass{i}", review="passed")
        conn.close()

        report = run_guardian_review("particle:alpha", graph_db=db)
        assert report.status == "GREEN"
        assert report.violations == 0
        assert report.total_behaviors == 10
        assert report.alerts == []

    def test_guardian_violations(self, tmp_path: Path) -> None:
        """Violation rate >= critical threshold (25%) returns RED with CRITICAL alert."""
        db = self._graph_db(tmp_path)
        conn = open_db(db)
        # 3 passed + 1 failed = 25% violation rate >= 0.25 critical threshold
        for i in range(3):
            self._insert_behavior(conn, "particle:alpha", f"entity:pass{i}", review="passed")
        self._insert_behavior(conn, "particle:alpha", "entity:fail", review="failed")
        conn.close()

        report = run_guardian_review("particle:alpha", graph_db=db)
        assert report.status == "RED"
        assert report.violations == 1
        assert report.total_behaviors == 4
        assert any(a.severity == "CRITICAL" for a in report.alerts)
        assert any("violation_rate" in a.source for a in report.alerts)

    def test_guardian_collusion(self, tmp_path: Path) -> None:
        """Active collusion flag above zero-threshold returns YELLOW with WARNING."""
        db = self._graph_db(tmp_path)
        conn = open_db(db)
        self._ensure(conn, "particle:alpha")
        self._ensure(conn, "entity:accomplice")
        conn.execute(
            """INSERT INTO collusion_flags (pattern, entity_a_id, entity_b_id, evidence)
               VALUES (?, ?, ?, ?)""",
            (
                "bid_rigging",
                "particle:alpha",
                "entity:accomplice",
                '{"detail": "suspicious pattern near simultaneous quotes"}',
            ),
        )
        conn.close()

        thresholds = load_guardian_thresholds("particle:alpha")
        thresholds["collusion_flags_warning"] = 0  # 1 flag triggers WARNING
        report = run_guardian_review("particle:alpha", thresholds=thresholds, graph_db=db)
        assert report.status == "YELLOW"
        assert report.collusion_flags == 1
        assert any(a.severity == "WARNING" for a in report.alerts)
        assert any("collusion" in a.source for a in report.alerts)

    def test_guardian_trust_drop(self, tmp_path: Path) -> None:
        """Trust score delta <= -10 returns YELLOW with declining trend."""
        db = self._graph_db(tmp_path)
        conn = open_db(db)
        # Two trust scores with different counterparties to get a -10 delta.
        # The query orders by updated_at ASC, so the older entry must be higher.
        self._ensure(conn, "particle:alpha")
        self._ensure(conn, "entity:other1")
        self._ensure(conn, "entity:other2")
        conn.execute(
            """INSERT INTO trust_scores (source_id, target_id, score, confidence, updated_at)
               VALUES (?, ?, ?, ?, ?)""",
            ("particle:alpha", "entity:other1", 80, 90, "2024-01-01T00:00:00Z"),
        )
        conn.execute(
            """INSERT INTO trust_scores (source_id, target_id, score, confidence, updated_at)
               VALUES (?, ?, ?, ?, ?)""",
            ("particle:alpha", "entity:other2", 70, 90, "2024-01-02T00:00:00Z"),
        )
        conn.close()

        report = run_guardian_review("particle:alpha", graph_db=db)
        assert report.status == "YELLOW"
        assert report.trust_trend == "declining"
        assert any(a.severity == "WARNING" for a in report.alerts)
        assert any("trust" in a.source for a in report.alerts)

    def test_guardian_empty_graph(self, tmp_path: Path) -> None:
        """Empty behavior graph returns GREEN — no data means no violation."""
        db = self._graph_db(tmp_path)
        report = run_guardian_review("particle:unknown", graph_db=db)
        assert report.status == "GREEN"
        assert report.total_behaviors == 0
        assert report.violations == 0
        assert report.collusion_flags == 0
        assert report.trust_trend == "stable"
        assert report.alerts == []

    def test_guardian_partial(self, tmp_path: Path) -> None:
        """5% violation rate (below 10% warning threshold) returns GREEN."""
        db = self._graph_db(tmp_path)
        conn = open_db(db)
        # 1 failed out of 20 = 5% < 10% warning threshold
        for i in range(19):
            self._insert_behavior(conn, "particle:alpha", f"entity:pass{i}", review="passed")
        self._insert_behavior(conn, "particle:alpha", "entity:fail", review="failed")
        conn.close()

        report = run_guardian_review("particle:alpha", graph_db=db)
        assert report.status == "GREEN"
        assert report.violations == 1
        assert report.total_behaviors == 20
        assert report.alerts == []
