apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image | quote }}
          ports:
            - containerPort: {{ .Values.zookeeper.port }}
              name: client
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.zookeeper.port | quote }}
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
