apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-deployment
  labels:
    app: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
        - name: blockchain
          image: {{ .Values.blockchain.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.blockchain.portHttp }}
              name: rpc-http
            - containerPort: {{ .Values.blockchain.portWs }}
              name: rpc-ws
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
