apiVersion: v1
kind: Service
metadata:
  name: ai
  labels:
    app: ai
spec:
  type: {{ .Values.service.ai.type }}
  ports:
    - port: {{ .Values.service.ai.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app: ai
