apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  ports:
    - port: {{ .Values.zookeeper.port }}
      targetPort: client
      protocol: TCP
  selector:
    app: zookeeper
