apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  labels:
    app: blockchain
spec:
  ports:
    - name: http
      port: {{ .Values.blockchain.portHttp }}
      targetPort: rpc-http
      protocol: TCP
    - name: ws
      port: {{ .Values.blockchain.portWs }}
      targetPort: rpc-ws
      protocol: TCP
  selector:
    app: blockchain
