import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-purple-950 to-slate-950">
      {/* Hero Section - Cyberpunk Enterprise */}
      <div className="relative overflow-hidden">
        {/* Neon Grid Background */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#4f4f4f2e_1px,transparent_1px),linear-gradient(to_bottom,#4f4f4f2e_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_80%_50%_at_50%_0%,#000_70%,transparent_110%)]" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-24">
          <div className="text-center space-y-8">
            {/* Badge */}
            <div className="inline-flex items-center rounded-full border border-cyan-500/50 bg-cyan-500/10 px-4 py-1.5 text-sm font-medium text-cyan-400 backdrop-blur">
              <span className="animate-pulse mr-2">●</span> Enterprise AI Infrastructure
            </div>

            {/* Hero Headline */}
            <h1 className="text-6xl md:text-7xl lg:text-8xl font-bold tracking-tight">
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 via-purple-400 to-pink-400 animate-gradient">
                ROI AS A SERVICE
              </span>
            </h1>

            {/* Subheadline */}
            <p className="text-xl md:text-2xl text-slate-300 max-w-3xl mx-auto leading-relaxed">
              Deploy autonomous AI agents that generate revenue 24/7.
              <br />
              <span className="text-cyan-400 font-semibold">No coding. No maintenance. Pure results.</span>
            </p>

            {/* CTA */}
            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-6">
              <Button
                size="lg"
                className="bg-gradient-to-r from-cyan-500 to-purple-500 hover:from-cyan-600 hover:to-purple-600 text-white font-semibold text-lg px-8 py-6 shadow-lg shadow-cyan-500/50"
              >
                Get Started →
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Feature Cards - Cyberpunk Style */}
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* AI Agents Card */}
          <Card className="bg-slate-900/50 border-cyan-500/30 backdrop-blur p-8 hover:border-cyan-400/60 transition-all group">
            <div className="space-y-4">
              <div className="text-4xl">🤖</div>
              <h3 className="text-2xl font-bold text-cyan-400 group-hover:text-cyan-300">
                AI Agents
              </h3>
              <p className="text-slate-400 leading-relaxed">
                Self-healing autonomous agents that plan, execute, and verify every task with military precision.
              </p>
              <div className="pt-2 text-cyan-500 text-sm font-mono">
                Plan → Execute → Verify
              </div>
            </div>
          </Card>

          {/* Auto Deploy Card */}
          <Card className="bg-slate-900/50 border-purple-500/30 backdrop-blur p-8 hover:border-purple-400/60 transition-all group">
            <div className="space-y-4">
              <div className="text-4xl">🚀</div>
              <h3 className="text-2xl font-bold text-purple-400 group-hover:text-purple-300">
                Auto Deploy
              </h3>
              <p className="text-slate-400 leading-relaxed">
                Zero-downtime deployments with intelligent rollback. Your revenue stream never sleeps.
              </p>
              <div className="pt-2 text-purple-500 text-sm font-mono">
                CI/CD → Production → Monitor
              </div>
            </div>
          </Card>

          {/* Revenue Track Card */}
          <Card className="bg-slate-900/50 border-pink-500/30 backdrop-blur p-8 hover:border-pink-400/60 transition-all group">
            <div className="space-y-4">
              <div className="text-4xl">📊</div>
              <h3 className="text-2xl font-bold text-pink-400 group-hover:text-pink-300">
                Revenue Track
              </h3>
              <p className="text-slate-400 leading-relaxed">
                Real-time analytics dashboard showing every dollar generated by your AI workforce.
              </p>
              <div className="pt-2 text-pink-500 text-sm font-mono">
                Monitor → Optimize → Scale
              </div>
            </div>
          </Card>
        </div>
      </div>
    </main>
  );
}
