# Mekong CLI — AI-Powered Business Operations for Vietnam
# MIT License. Copyright (c) 2026 MekongMind. See LICENSE file.

"""Generate shell completion packages from command fabric records."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from src.command_fabric.catalog import CommandRecord, build_command_catalog


@dataclass(frozen=True)
class ShellCompletionArtifact:
    """One generated shell completion package file."""

    name: str
    path: str
    command_count: int


def _shell_words(records: list[CommandRecord]) -> str:
    return " ".join(record.name for record in sorted(records, key=lambda item: item.name))


def bash_completion(records: list[CommandRecord]) -> str:
    """Return Bash completion script for Mekong root commands."""
    words = _shell_words(records)
    return f"""# Generated by Mekong command fabric.
_mekong_completions() {{
  local cur
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "{words}" -- "$cur") )
  else
    COMPREPLY=()
  fi
}}
complete -F _mekong_completions mekong
"""


def zsh_completion(records: list[CommandRecord]) -> str:
    """Return Zsh completion script for Mekong root commands."""
    entries = " ".join(
        f"'{record.name}:{(record.description or record.name).replace(':', '-')}'"
        for record in sorted(records, key=lambda item: item.name)
    )
    return f"""#compdef mekong
# Generated by Mekong command fabric.
_mekong() {{
  _arguments '1:command:(({entries}))' '*::arguments:_normal'
}}
_mekong "$@"
"""


def fish_completion(records: list[CommandRecord]) -> str:
    """Return Fish completion script for Mekong root commands."""
    lines = ["# Generated by Mekong command fabric."]
    for record in sorted(records, key=lambda item: item.name):
        desc = (record.description or record.name).replace("'", "")
        lines.append(
            f"complete -c mekong -f -n '__fish_use_subcommand' "
            f"-a '{record.name}' -d '{desc}'"
        )
    return "\n".join(lines) + "\n"


def powershell_completion(records: list[CommandRecord]) -> str:
    """Return PowerShell completion script for Mekong root commands."""
    quoted_names = []
    for record in sorted(records, key=lambda item: item.name):
        quoted_names.append("'" + record.name.replace("'", "''") + "'")
    entries = ", ".join(quoted_names)
    return f"""# Generated by Mekong command fabric.
$MekongCommands = @({entries})
Register-ArgumentCompleter -Native -CommandName mekong -ScriptBlock {{
  param($wordToComplete, $commandAst, $cursorPosition)
  $MekongCommands |
    Where-Object {{ $_ -like "$wordToComplete*" }} |
    ForEach-Object {{ [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }}
}}
"""


def nushell_completion(records: list[CommandRecord]) -> str:
    """Return Nushell completion script for Mekong root commands."""
    rows = []
    for record in sorted(records, key=lambda item: item.name):
        name = record.name.replace('"', '\\"')
        description = (record.description or record.name).replace('"', '\\"')
        rows.append(f'  {{ value: "{name}", description: "{description}" }}')
    body = "\n".join(rows)
    return f"""# Generated by Mekong command fabric.
export extern "mekong" [
  command?: string@mekong_commands
  ...args: string
]

def mekong_commands [] {{
{body}
}}
"""


def elvish_completion(records: list[CommandRecord]) -> str:
    """Return Elvish completion script for Mekong root commands."""
    lines = []
    for record in sorted(records, key=lambda item: item.name):
        escaped = record.name.replace("\\", "\\\\").replace(" ", "\\ ")
        lines.append(f"  put {escaped}")
    rows = "\n".join(lines)
    return f"""# Generated by Mekong command fabric.
set edit:completion:arg-completer[mekong] = {{
  if (== (count $words) 2) {{
{rows}
  }}
}}
"""


def install_sh() -> str:
    """Return a small installer for generated shell completion files."""
    return """#!/usr/bin/env sh
set -eu

TARGET="${1:-$HOME/.mekong/completions}"
mkdir -p "$TARGET"
cp bash/mekong.bash "$TARGET/mekong.bash"
cp zsh/_mekong "$TARGET/_mekong"
cp fish/mekong.fish "$TARGET/mekong.fish"
cp powershell/mekong.ps1 "$TARGET/mekong.ps1"
cp nushell/mekong.nu "$TARGET/mekong.nu"
cp elvish/mekong.elv "$TARGET/mekong.elv"

printf '%s\\n' "Installed Mekong completions to $TARGET"
printf '%s\\n' "Bash: source $TARGET/mekong.bash"
printf '%s\\n' "Zsh: add $TARGET to fpath, then run compinit"
printf '%s\\n' "Fish: copy $TARGET/mekong.fish to ~/.config/fish/completions/"
printf '%s\\n' "PowerShell: dot-source $TARGET/mekong.ps1 from your profile"
printf '%s\\n' "Nushell: use $TARGET/mekong.nu from your config"
printf '%s\\n' "Elvish: source $TARGET/mekong.elv from rc.elv"
"""


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def materialize_shell_completion(
    output_dir: Path,
    records: list[CommandRecord] | None = None,
) -> dict[str, object]:
    """Write shell completion artifacts and installer."""
    command_records = records if records is not None else build_command_catalog()
    root = output_dir / "shell"
    files = [
        ("bash", root / "bash" / "mekong.bash", bash_completion(command_records)),
        ("zsh", root / "zsh" / "_mekong", zsh_completion(command_records)),
        ("fish", root / "fish" / "mekong.fish", fish_completion(command_records)),
        ("powershell", root / "powershell" / "mekong.ps1", powershell_completion(command_records)),
        ("nushell", root / "nushell" / "mekong.nu", nushell_completion(command_records)),
        ("elvish", root / "elvish" / "mekong.elv", elvish_completion(command_records)),
        ("installer", root / "install.sh", install_sh()),
    ]
    for _, path, content in files:
        _write(path, content)

    artifacts = [
        ShellCompletionArtifact(name, path.as_posix(), len(command_records))
        for name, path, _ in files
    ]
    return {
        "schema": "mekong.command_fabric.shell_completion.v1",
        "host": "shell",
        "command_count": len(command_records),
        "artifacts": [artifact.__dict__ for artifact in artifacts],
    }


__all__ = [
    "ShellCompletionArtifact",
    "bash_completion",
    "elvish_completion",
    "fish_completion",
    "install_sh",
    "materialize_shell_completion",
    "nushell_completion",
    "powershell_completion",
    "zsh_completion",
]
