"""Performance reporting — public-facing trading performance data.

Generates weekly blog-ready performance reports and
live dashboard data for transparency marketing.
"""

from __future__ import annotations

import logging
import os
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

DB_PATH = os.getenv("DATABASE_PATH", "data/algo-trade.db")
REPORTS_DIR = "data/reports"


def generate_weekly_report(week_offset: int = 0) -> str:
    """Generate weekly performance report for blog/transparency.

    Args:
        week_offset: 0 = current week, -1 = last week, etc.
    """
    now = datetime.utcnow()
    week_start = now - timedelta(days=now.weekday() + 7 * abs(week_offset))
    week_end = week_start + timedelta(days=7)
    week_label = week_start.strftime("%Y-W%W")

    if not Path(DB_PATH).exists():
        return f"# CashClaw Week {week_label}\n\nNo trading data available.\n"

    try:
        with sqlite3.connect(DB_PATH) as conn:
            rows = conn.execute(
                """SELECT predicted_probability, actual_outcome, pnl,
                          edge, direction, market_id, question
                   FROM ai_decisions
                   WHERE resolved = 1
                     AND date(timestamp) >= date(?)
                     AND date(timestamp) < date(?)""",
                (week_start.strftime("%Y-%m-%d"), week_end.strftime("%Y-%m-%d")),
            ).fetchall()

        total = len(rows)
        if total == 0:
            return f"# CashClaw Week {week_label}\n\nNo resolved trades this week.\n"

        predicted = [r[0] for r in rows]
        actual = [r[1] for r in rows]
        pnls = [r[2] or 0 for r in rows]
        edges = [r[3] or 0 for r in rows]

        brier = sum((p - a) ** 2 for p, a in zip(predicted, actual)) / total
        win_rate = sum(1 for p in pnls if p > 0) / total
        total_pnl = sum(pnls)
        avg_edge = sum(edges) / total
        best_trade = max(pnls)
        worst_trade = min(pnls)

        report = f"""# CashClaw Week {week_label} Performance Report

## Summary

| Metric | Value |
|--------|-------|
| Total Trades | {total} |
| Win Rate | {win_rate * 100:.1f}% |
| Brier Score | {brier:.4f} |
| Total P&L | {total_pnl:+.1f}% |
| Avg Edge | {avg_edge * 100:.1f}% |
| Best Trade | {best_trade:+.1f}% |
| Worst Trade | {worst_trade:+.1f}% |

## Calibration

Brier score of {brier:.4f} {"meets" if brier < 0.20 else "exceeds"} our target of 0.20.

## Trade Breakdown

| Direction | Count | Win Rate |
|-----------|-------|----------|
| YES | {sum(1 for r in rows if r[4] == 'YES')} | — |
| NO | {sum(1 for r in rows if r[4] == 'NO')} | — |

---

*Generated by CashClaw AI Trading Engine. Past performance does not guarantee future results.*
"""
        return report

    except Exception:
        logger.exception("Error generating weekly report")
        return f"# CashClaw Week {week_label}\n\nError generating report.\n"


def save_weekly_report(week_offset: int = 0) -> str:
    """Generate and save weekly report to file."""
    report = generate_weekly_report(week_offset)

    now = datetime.utcnow()
    week_start = now - timedelta(days=now.weekday() + 7 * abs(week_offset))
    week_label = week_start.strftime("%Y-W%W")

    Path(REPORTS_DIR).mkdir(parents=True, exist_ok=True)
    path = f"{REPORTS_DIR}/weekly-{week_label}.md"
    Path(path).write_text(report)

    logger.info("Weekly report saved: %s", path)
    return path


def get_all_time_stats() -> dict:
    """Get all-time performance statistics for marketing."""
    if not Path(DB_PATH).exists():
        return {"total_trades": 0, "win_rate": 0, "brier": None}

    try:
        with sqlite3.connect(DB_PATH) as conn:
            total = conn.execute(
                "SELECT COUNT(*) FROM ai_decisions WHERE resolved = 1"
            ).fetchone()[0]

            if total == 0:
                return {"total_trades": 0, "win_rate": 0, "brier": None}

            wins = conn.execute(
                "SELECT COUNT(*) FROM ai_decisions WHERE resolved = 1 AND pnl > 0"
            ).fetchone()[0]

            rows = conn.execute(
                "SELECT predicted_probability, actual_outcome FROM ai_decisions WHERE resolved = 1"
            ).fetchall()

            brier = sum((p - a) ** 2 for p, a in rows) / len(rows)

        return {
            "total_trades": total,
            "win_rate": round(wins / total, 3),
            "brier": round(brier, 4),
            "sample_size": total,
        }
    except Exception:
        return {"total_trades": 0, "win_rate": 0, "brier": None}
