"""Gateway module - exports models and functions from gateway.py"""

# Import everything from gateway.py for backward compatibility
from src.core.gateway.gateway_main import (
    create_app,
    app,
    verify_token,
    build_human_summary,
    _scan_projects,
    _build_orchestrator,
    _build_cmd_response,
    CommandRequest,
    CommandResponse,
    StepSummary,
    HumanSummary,
    HealthResponse,
    PresetAction,
    ProjectInfo,
    SwarmNodeInfo,
    SwarmRegisterRequest,
    SwarmDispatchRequest,
    ScheduleJobInfo,
    ScheduleAddRequest,
    MemoryEntryInfo,
    MemoryStatsResponse,
    NLUParseRequest,
    NLUParseResponse,
    RecipeGenerateRequest,
    RecipeGenerateResponse,
    RecipeValidateRequest,
    RecipeValidateResponse,
    AutoRecipeInfo,
    GovernanceCheckRequest,
    HaltRequest,
    PRESET_ACTIONS,
    GATEWAY_CONFIG,
    VERSION,
)
from src.core.orchestrator import RecipeOrchestrator, OrchestrationResult
from src.core.llm_client import get_client

__all__ = [
    "create_app",
    "app",
    "verify_token",
    "build_human_summary",
    "_scan_projects",
    "_build_orchestrator",
    "_build_cmd_response",
    "CommandRequest",
    "CommandResponse",
    "StepSummary",
    "HumanSummary",
    "HealthResponse",
    "PresetAction",
    "ProjectInfo",
    "SwarmNodeInfo",
    "SwarmRegisterRequest",
    "SwarmDispatchRequest",
    "ScheduleJobInfo",
    "ScheduleAddRequest",
    "MemoryEntryInfo",
    "MemoryStatsResponse",
    "NLUParseRequest",
    "NLUParseResponse",
    "RecipeGenerateRequest",
    "RecipeGenerateResponse",
    "RecipeValidateRequest",
    "RecipeValidateResponse",
    "AutoRecipeInfo",
    "GovernanceCheckRequest",
    "HaltRequest",
    "PRESET_ACTIONS",
    "GATEWAY_CONFIG",
    "VERSION",
    "RecipeOrchestrator",
    "OrchestrationResult",
    "get_client",
]
