# Mekong CLI — AI-Powered Business Operations for Vietnam
# MIT License. Copyright (c) 2026 MekongMind. See LICENSE file.

"""Gateway module - exports models and functions from gateway.py."""

# Import everything from gateway.py for backward compatibility
from src.core.gateway.gateway_main import (
    GATEWAY_CONFIG,
    PRESET_ACTIONS,
    VERSION,
    AutoRecipeInfo,
    CommandRequest,
    CommandResponse,
    GovernanceCheckRequest,
    HaltRequest,
    HealthResponse,
    HumanSummary,
    MemoryEntryInfo,
    MemoryStatsResponse,
    NLUParseRequest,
    NLUParseResponse,
    PresetAction,
    ProjectInfo,
    RecipeGenerateRequest,
    RecipeGenerateResponse,
    RecipeValidateRequest,
    RecipeValidateResponse,
    ScheduleAddRequest,
    ScheduleJobInfo,
    StepSummary,
    SwarmDispatchRequest,
    SwarmNodeInfo,
    SwarmRegisterRequest,
    _build_cmd_response,
    _build_orchestrator,
    _scan_projects,
    app,
    build_human_summary,
    create_app,
    verify_token,
)
from src.providers.llm.client import get_client
from src.core.orchestrator import OrchestrationResult, RecipeOrchestrator
from src.core.gateway.streaming import (
    ControlCommand,
    EventSubscriber,
    MissionStreamingBroker,
    StreamEvent,
    StreamEventType,
    WebSocketFrameParser,
    format_sse_event,
    get_mission_streaming_broker,
    handle_websocket_duplex,
    set_mission_streaming_broker,
    stream_events_sse,
)
from src.core.gateway.rate_limiter import (
    GatewayTelemetryHub,
    RateLimitDecision,
    RateLimitQuota,
    RateLimitResult,
    RateLimitTier,
    SlidingWindowRateLimiter,
    TIER_QUOTAS,
    TenantBucket,
    TenantTier,
    TierQuota,
    get_rate_limiter,
    get_telemetry_hub,
    set_rate_limiter,
    set_telemetry_hub,
)

__all__ = [
    "GATEWAY_CONFIG",
    "PRESET_ACTIONS",
    "VERSION",
    "AutoRecipeInfo",
    "CommandRequest",
    "CommandResponse",
    "GovernanceCheckRequest",
    "HaltRequest",
    "HealthResponse",
    "HumanSummary",
    "MemoryEntryInfo",
    "MemoryStatsResponse",
    "NLUParseRequest",
    "NLUParseResponse",
    "OrchestrationResult",
    "PresetAction",
    "ProjectInfo",
    "RecipeGenerateRequest",
    "RecipeGenerateResponse",
    "RecipeOrchestrator",
    "RecipeValidateRequest",
    "RecipeValidateResponse",
    "ScheduleAddRequest",
    "ScheduleJobInfo",
    "StepSummary",
    "SwarmDispatchRequest",
    "SwarmNodeInfo",
    "SwarmRegisterRequest",
    "_build_cmd_response",
    "_build_orchestrator",
    "_scan_projects",
    "app",
    "build_human_summary",
    "create_app",
    "get_client",
    "verify_token",
    # Streaming exports
    "ControlCommand",
    "EventSubscriber",
    "MissionStreamingBroker",
    "StreamEvent",
    "StreamEventType",
    "WebSocketFrameParser",
    "format_sse_event",
    "get_mission_streaming_broker",
    "handle_websocket_duplex",
    "set_mission_streaming_broker",
    "stream_events_sse",
    # Rate limiter & Telemetry exports
    "GatewayTelemetryHub",
    "RateLimitDecision",
    "RateLimitQuota",
    "RateLimitResult",
    "RateLimitTier",
    "SlidingWindowRateLimiter",
    "TIER_QUOTAS",
    "TenantBucket",
    "TenantTier",
    "TierQuota",
    "get_rate_limiter",
    "get_telemetry_hub",
    "set_rate_limiter",
    "set_telemetry_hub",
]
