import type { KPISnapshot } from './pitch-generator.js';

export interface AgendaItem {
  topic: string;
  presenter: string;
  duration: string;
  type: 'update' | 'discussion' | 'vote' | 'action';
}

export interface BoardAgenda {
  date: string;
  items: AgendaItem[];
}

export interface MeetingMinutes {
  date: string;
  attendees: string[];
  decisions: string[];
  actionItems: Array<{ task: string; owner: string; due: string }>;
}

export interface InvestorUpdate {
  period: string;
  highlights: string[];
  kpis: KPISnapshot;
  nextSteps: string[];
}

const STANDARD_AGENDA_ITEMS: Array<Omit<AgendaItem, 'duration'>> = [
  { topic: 'Call to order & quorum confirmation', presenter: 'Chair', type: 'action' },
  { topic: 'Approval of prior meeting minutes', presenter: 'Secretary', type: 'vote' },
  { topic: 'Financial review — P&L, cash runway', presenter: 'CFO', type: 'update' },
  { topic: 'KPI dashboard review', presenter: 'CEO', type: 'update' },
  { topic: 'Product & engineering update', presenter: 'CTO', type: 'update' },
  { topic: 'Sales & GTM performance', presenter: 'CRO', type: 'update' },
  { topic: 'Strategic discussion — key initiatives', presenter: 'CEO', type: 'discussion' },
  { topic: 'Fundraising & investor relations', presenter: 'CEO', type: 'update' },
  { topic: 'Board votes & resolutions', presenter: 'Chair', type: 'vote' },
  { topic: 'AOB & next meeting date', presenter: 'Chair', type: 'action' },
];

const ITEM_DURATIONS: Record<AgendaItem['type'], string> = {
  action: '5 min',
  vote: '10 min',
  update: '15 min',
  discussion: '20 min',
};

function formatKPI(value: number, prefix = '', suffix = ''): string {
  return `${prefix}${value.toLocaleString()}${suffix}`;
}

export class BoardMeeting {
  private minutes: MeetingMinutes[] = [];

  generateAgenda(date: string): BoardAgenda {
    const items: AgendaItem[] = STANDARD_AGENDA_ITEMS.map((item) => ({
      ...item,
      duration: ITEM_DURATIONS[item.type],
    }));
    return { date, items };
  }

  generateKPIDashboard(kpis: KPISnapshot): string {
    const arr = kpis.mrr * 12;
    const growthPct = (kpis.growth * 100).toFixed(1);
    const churnPct = (kpis.churn * 100).toFixed(2);
    const ltv = kpis.mrr / Math.max(kpis.churn, 0.001);
    const mrrFormatted = kpis.mrr >= 1_000_000
      ? `$${(kpis.mrr / 1_000_000).toFixed(2)}M`
      : `$${(kpis.mrr / 1_000).toFixed(0)}K`;
    const arrFormatted = arr >= 1_000_000
      ? `$${(arr / 1_000_000).toFixed(2)}M`
      : `$${(arr / 1_000).toFixed(0)}K`;

    return `## KPI Dashboard

| Metric | Value | Trend |
|--------|-------|-------|
| MRR | ${mrrFormatted} | +${growthPct}% MoM |
| ARR | ${arrFormatted} | — |
| Active Users | ${formatKPI(kpis.users)} | — |
| MoM Growth | ${growthPct}% | — |
| Churn Rate | ${churnPct}% | — |
| Estimated LTV | $${ltv.toFixed(0)} | — |

> *Dashboard generated ${new Date().toISOString().split('T')[0]}*
`;
  }

  recordMinutes(meeting: MeetingMinutes): void {
    this.minutes.push({ ...meeting });
  }

  getMinutes(): MeetingMinutes[] {
    return [...this.minutes];
  }

  generateInvestorUpdate(period: string): string {
    const lastMinutes = this.minutes[this.minutes.length - 1];
    const decisions = lastMinutes?.decisions ?? ['No decisions recorded.'];
    const actionItems = lastMinutes?.actionItems ?? [];

    const decisionsText = decisions.map((d) => `- ${d}`).join('\n');
    const actionText = actionItems.length > 0
      ? actionItems.map((a) => `- **${a.task}** — ${a.owner} (due ${a.due})`).join('\n')
      : '- No open action items.';

    return `# Investor Update — ${period}

Hi team,

Here's your ${period} update from the board.

## Highlights

- Strong execution across product and go-to-market.
- Key decisions ratified at board meeting.
- Pipeline momentum building.

## Key Decisions

${decisionsText}

## Open Action Items

${actionText}

## What's Next

- Continue executing on current OKRs.
- Next board meeting scheduled in 30 days.
- Fundraising process update in next update.

Thank you for your continued support.

— The Management Team

---
*Generated by OpenClaw VC Governance. Confidential — do not distribute.*
`;
  }
}
