export type DocCategory = 'legal' | 'financial' | 'product' | 'team';

export interface DataRoomDoc {
  name: string;
  category: DocCategory;
  content: string;
  uploadedAt: Date;
}

export interface Shareholder {
  name: string;
  shares: number;
  type: 'founder' | 'investor' | 'employee';
}

export interface CapTableEntry extends Shareholder {
  percentage: number;
}

export interface CapTable {
  shareholders: CapTableEntry[];
  totalShares: number;
  breakdown: Record<Shareholder['type'], { shares: number; percentage: number }>;
}

export interface TermSheetInput {
  investor: string;
  amount: number;
  valuation: number;
  type: 'priced' | 'safe' | 'convertible';
}

function formatUSD(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  return `$${n.toLocaleString()}`;
}

function formatDate(d: Date): string {
  return d.toISOString().split('T')[0];
}

export class DataRoom {
  private documents: DataRoomDoc[] = [];

  addDocument(doc: DataRoomDoc): void {
    this.documents.push({ ...doc });
  }

  listDocuments(category?: DocCategory): DataRoomDoc[] {
    if (!category) return [...this.documents];
    return this.documents.filter((d) => d.category === category);
  }

  generateCapTable(shareholders: Shareholder[]): CapTable {
    const totalShares = shareholders.reduce((sum, s) => sum + s.shares, 0);
    if (totalShares === 0) throw new Error('Total shares cannot be zero.');

    const entries: CapTableEntry[] = shareholders.map((s) => ({
      ...s,
      percentage: (s.shares / totalShares) * 100,
    }));

    const types: Shareholder['type'][] = ['founder', 'investor', 'employee'];
    const breakdown = Object.fromEntries(
      types.map((t) => {
        const group = entries.filter((e) => e.type === t);
        const shares = group.reduce((sum, e) => sum + e.shares, 0);
        return [t, { shares, percentage: (shares / totalShares) * 100 }];
      }),
    ) as CapTable['breakdown'];

    return { shareholders: entries, totalShares, breakdown };
  }

  generateSAFE(investor: string, amount: number, valuationCap: number): string {
    const today = formatDate(new Date());
    return `# Simple Agreement for Future Equity (SAFE)

**Date:** ${today}
**Investor:** ${investor}
**Purchase Amount:** ${formatUSD(amount)}
**Valuation Cap:** ${formatUSD(valuationCap)}
**Discount Rate:** 20%

## Terms

1. **Investment.** Investor agrees to purchase, and the Company agrees to issue, the right to receive shares of the Company's capital stock upon the terms set forth herein.

2. **Conversion.** This SAFE will convert into shares upon an Equity Financing at the lower of:
   - The price per share at a valuation of ${formatUSD(valuationCap)} (the "Valuation Cap"), or
   - An 80% discount to the price per share in the Equity Financing.

3. **Dissolution.** Upon a dissolution event, the Investor receives back the Purchase Amount before any distribution to stockholders.

4. **Liquidity.** Upon a liquidity event, the Investor receives the greater of (a) the Purchase Amount or (b) the amount payable on an as-converted basis.

5. **Governing Law.** This SAFE is governed by the laws of Delaware.

---
*This SAFE was generated by OpenClaw VC Governance. Consult legal counsel before execution.*
`;
  }

  generateTermSheet(terms: TermSheetInput): string {
    const today = formatDate(new Date());
    const ownership = ((terms.amount / (terms.valuation + terms.amount)) * 100).toFixed(2);
    const pricePerShare = (terms.valuation / 10_000_000).toFixed(4);

    return `# Term Sheet — ${terms.type.toUpperCase()} Round

**Date:** ${today}
**Investor:** ${terms.investor}
**Investment Amount:** ${formatUSD(terms.amount)}
**Pre-Money Valuation:** ${formatUSD(terms.valuation)}
**Post-Money Valuation:** ${formatUSD(terms.valuation + terms.amount)}
**Implied Ownership:** ${ownership}%

## Key Terms

| Term | Value |
|------|-------|
| Round Type | ${terms.type} |
| Price Per Share | $${pricePerShare} |
| Liquidation Preference | 1x non-participating |
| Anti-Dilution | Broad-based weighted average |
| Pro-Rata Rights | Yes |
| Information Rights | Quarterly financials |
| Board Seat | ${terms.amount >= 2_000_000 ? 'Observer seat' : 'None'} |
| Drag-Along | Standard |
| Exclusivity | 30 days |

## Conditions

- Satisfactory due diligence
- Legal documentation acceptable to both parties
- No material adverse change

---
*This term sheet is non-binding. Final terms subject to definitive agreements.*
`;
  }
}
