"""
Improvement Engine — Generate improvement tasks from failure analysis.

Features:
- Analyzes failure patterns from journal
- Generates corrective tasks automatically
- Creates improvement recommendations
- Tracks improvement effectiveness

Usage:
  engine = ImprovementEngine()
  tasks = engine.analyze_and_generate_tasks()
  recommendations = engine.get_recommendations()
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from .learning_journal import LearningJournal
from .pattern_library import PatternLibrary

logger = logging.getLogger(__name__)

MEKONG_ROOT = Path(__file__).parent.parent.parent
MEKONG_DIR = MEKONG_ROOT / ".mekong"
JOURNAL_DIR = MEKONG_DIR / "journal"
IMPROVEMENTS_FILE = JOURNAL_DIR / "improvements.json"

# Ensure directory exists
JOURNAL_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class ImprovementTask:
    """An improvement task generated by the engine."""

    id: str
    title: str
    description: str
    priority: str  # CRITICAL, HIGH, MEDIUM, LOW
    category: str  # reliability, performance, security, tech_debt
    source_analysis: str
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    status: str = "pending"  # pending, in_progress, completed, cancelled
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "priority": self.priority,
            "category": self.category,
            "source_analysis": self.source_analysis,
            "created_at": self.created_at,
            "status": self.status,
            "metadata": self.metadata,
        }


@dataclass
class ImprovementRecommendation:
    """A recommendation for improvement."""

    category: str
    description: str
    impact: str  # high, medium, low
    effort: str  # low, medium, high
    details: dict[str, Any] = field(default_factory=dict)


class ImprovementEngine:
    """
    Analyzes failures and generates improvement tasks.

    Analysis includes:
    - Repeated failure patterns
    - High-impact failure categories
    - Tech debt accumulation
    - Performance degradation
    """

    def __init__(
        self,
        journal: LearningJournal | None = None,
        pattern_library: PatternLibrary | None = None,
    ) -> None:
        self.journal = journal or LearningJournal()
        self.pattern_library = pattern_library or PatternLibrary()
        self._improvements: list[ImprovementTask] = []
        self._recommendations: list[ImprovementRecommendation] = []
        self._load()

    def _load(self) -> None:
        """Load improvements from disk."""
        if not IMPROVEMENTS_FILE.exists():
            return

        try:
            data = json.loads(IMPROVEMENTS_FILE.read_text())
            for imp_data in data.get("improvements", []):
                improvement = ImprovementTask(
                    id=imp_data["id"],
                    title=imp_data["title"],
                    description=imp_data["description"],
                    priority=imp_data["priority"],
                    category=imp_data["category"],
                    source_analysis=imp_data["source_analysis"],
                    created_at=imp_data.get("created_at", ""),
                    status=imp_data.get("status", "pending"),
                    metadata=imp_data.get("metadata", {}),
                )
                self._improvements.append(improvement)
            logger.info(f"[ImprovementEngine] Loaded {len(self._improvements)} improvements")
        except (json.JSONDecodeError, KeyError) as e:
            logger.warning(f"[ImprovementEngine] Failed to load improvements: {e}")

    def _save(self) -> None:
        """Save improvements to disk."""
        data = {
            "improvements": [imp.to_dict() for imp in self._improvements],
            "last_updated": datetime.now().isoformat(),
        }
        IMPROVEMENTS_FILE.write_text(json.dumps(data, indent=2))

    def analyze_and_generate_tasks(
        self,
        lookback_days: int = 7,
        min_failures: int = 3,
    ) -> list[ImprovementTask]:
        """
        Analyze recent failures and generate improvement tasks.

        Args:
            lookback_days: Days of history to analyze
            min_failures: Minimum failures to trigger task generation

        Returns:
            List of generated ImprovementTask objects.
        """
        tasks = []

        # Get failure stats by category
        failure_stats = self._analyze_failure_patterns(lookback_days)

        # Generate tasks for repeated failures
        for category, stats in failure_stats.items():
            if stats["count"] >= min_failures:
                task = self._create_improvement_task(
                    category=category,
                    failure_count=stats["count"],
                    common_errors=stats["common_errors"],
                )
                tasks.append(task)
                self._improvements.append(task)

        # Generate tech debt task if applicable
        tech_debt_task = self._analyze_tech_debt()
        if tech_debt_task:
            tasks.append(tech_debt_task)
            self._improvements.append(tech_debt_task)

        # Save to disk
        self._save()

        logger.info(f"[ImprovementEngine] Generated {len(tasks)} improvement tasks")
        return tasks

    def _analyze_failure_patterns(self, lookback_days: int) -> dict[str, Any]:
        """Analyze failure patterns from the journal."""
        cutoff = (datetime.now() - timedelta(days=lookback_days)).isoformat()

        # Get failed missions
        failed = [
            m for m in self.journal.get_missions(limit=1000)
            if m["status"] == "failed" and m.get("created_at", "") > cutoff
        ]

        # Group by category/capability
        stats: dict[str, dict] = {}
        for mission in failed:
            capability = mission.get("capability", "general")
            if capability not in stats:
                stats[capability] = {"count": 0, "common_errors": []}
            stats[capability]["count"] += 1

            error = mission.get("error", "")
            if error and error not in stats[capability]["common_errors"]:
                stats[capability]["common_errors"].append(error[:100])

        return stats

    def _create_improvement_task(
        self,
        category: str,
        failure_count: int,
        common_errors: list[str],
    ) -> ImprovementTask:
        """Create an improvement task for a failure category."""
        # Determine priority based on failure count
        if failure_count >= 10:
            priority = "CRITICAL"
        elif failure_count >= 5:
            priority = "HIGH"
        elif failure_count >= 3:
            priority = "MEDIUM"
        else:
            priority = "LOW"

        task_id = f"improve-{category}-{datetime.now().strftime('%Y%m%d')}"

        description = f"""
Address recurring failures in {category} category.

Failure count: {failure_count}

Common errors:
{chr(10).join(f'- {e}' for e in common_errors[:5])}

Recommended actions:
1. Review error patterns and root causes
2. Implement fixes or workarounds
3. Add tests to prevent regression
4. Update documentation if needed
""".strip()

        return ImprovementTask(
            id=task_id,
            title=f"Fix recurring {category} failures",
            description=description,
            priority=priority,
            category="reliability",
            source_analysis=f"failure_pattern_analysis:{failure_count}_failures",
            metadata={"failure_count": failure_count, "common_errors": common_errors},
        )

    def _analyze_tech_debt(self) -> ImprovementTask | None:
        """Analyze tech debt and create improvement task if needed."""
        # Check for patterns that indicate tech debt
        missions = self.journal.get_missions(limit=500)

        # Count missions with tech debt indicators
        tech_debt_indicators = ["TODO", "FIXME", "hack", "temporary", "workaround"]
        tech_debt_count = sum(
            1 for m in missions
            if any(indicator in m.get("description", "").lower() for indicator in tech_debt_indicators)
        )

        if tech_debt_count >= 5:
            return ImprovementTask(
                id=f"tech-debt-{datetime.now().strftime('%Y%m%d')}",
                title="Reduce technical debt",
                description=f"""
Address accumulated technical debt.

Tech debt indicators found in {tech_debt_count} recent missions.

Recommended actions:
1. Review and prioritize TODO/FIXME comments
2. Refactor temporary solutions
3. Remove workaround code
4. Update documentation
""".strip(),
                priority="MEDIUM",
                category="tech_debt",
                source_analysis=f"tech_debt_analysis:{tech_debt_count}_indicators",
                metadata={"tech_debt_count": tech_debt_count},
            )

        return None

    def get_recommendations(self) -> list[ImprovementRecommendation]:
        """Get improvement recommendations based on analysis."""
        recommendations = []

        # Get summary stats
        summary = self.journal.get_summary()

        # Low success rate recommendation
        if summary["success_rate"] < 80:
            recommendations.append(ImprovementRecommendation(
                category="reliability",
                description="Improve mission success rate",
                impact="high",
                effort="medium",
                details={"current_success_rate": summary["success_rate"]},
            ))

        # High duration recommendation
        if summary["avg_duration_ms"] > 300000:  # 5 minutes
            recommendations.append(ImprovementRecommendation(
                category="performance",
                description="Reduce mission execution time",
                impact="medium",
                effort="high",
                details={"avg_duration_ms": summary["avg_duration_ms"]},
            ))

        self._recommendations = recommendations
        return recommendations

    def get_improvements(self, status: str | None = None) -> list[dict]:
        """Get improvement tasks, optionally filtered by status."""
        improvements = self._improvements
        if status:
            improvements = [imp for imp in improvements if imp.status == status]

        return [imp.to_dict() for imp in improvements]

    def mark_completed(self, improvement_id: str) -> bool:
        """Mark an improvement task as completed."""
        for imp in self._improvements:
            if imp.id == improvement_id:
                imp.status = "completed"
                self._save()
                logger.info(f"[ImprovementEngine] Marked {improvement_id} as completed")
                return True
        return False

    def get_stats(self) -> dict[str, Any]:
        """Get improvement engine statistics."""
        return {
            "total_improvements": len(self._improvements),
            "pending": sum(1 for imp in self._improvements if imp.status == "pending"),
            "completed": sum(1 for imp in self._improvements if imp.status == "completed"),
            "by_priority": self._count_by_priority(),
            "by_category": self._count_by_category(),
        }

    def _count_by_priority(self) -> dict[str, int]:
        """Count improvements by priority."""
        counts: dict[str, int] = {}
        for imp in self._improvements:
            counts[imp.priority] = counts.get(imp.priority, 0) + 1
        return counts

    def _count_by_category(self) -> dict[str, int]:
        """Count improvements by category."""
        counts: dict[str, int] = {}
        for imp in self._improvements:
            counts[imp.category] = counts.get(imp.category, 0) + 1
        return counts
