/**
 * AGI Level 6: Strategic Brain — 始計 Proactive Mission Generation
 *
 * 📜 Binh Pháp Ch.1 始計: 「未戰而廟算勝者」
 *    "Win before battle through superior planning"
 *
 * When all projects scan GREEN, the CTO doesn't idle — it IMPROVES:
 *   1. Consult learning insights (Level 5 feedback)
 *   2. Pick strategic task weighted by history + priority
 *   3. Generate proactive improvement mission
 *   4. Track outcomes for future optimization
 *
 * Cooldown: 30 min per project prevents token waste (Ch.2 作戰: 日費千金)
 */

const fs = require('fs');
const path = require('path');
const config = require('../config');
const { log } = require('./brain-process-manager');

const STRATEGIC_STATE_FILE = path.join(config.MEKONG_DIR, 'apps/openclaw-worker/data/strategic-state.json');
const INSIGHTS_FILE = path.join(config.MEKONG_DIR, 'apps/openclaw-worker/data/learning-insights.json');
const COOLDOWN_MS = 2 * 60 * 1000; // 2 minutes — fast iteration for single-project focus

// Ensure data dir exists
const DATA_DIR = path.dirname(STRATEGIC_STATE_FILE);
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

// --- State Management ---

function loadStrategicState() {
  try {
    if (fs.existsSync(STRATEGIC_STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STRATEGIC_STATE_FILE, 'utf-8'));
    }
  } catch (e) { }
  return {};
}

function saveStrategicState(state) {
  try {
    fs.writeFileSync(STRATEGIC_STATE_FILE, JSON.stringify(state, null, 2));
  } catch (e) {
    log(`[STRATEGIC] Failed to save state: ${e.message}`);
  }
}

// --- Learning Insights Integration ---

function getFailedTaskIds() {
  try {
    if (!fs.existsSync(INSIGHTS_FILE)) return [];
    const insights = JSON.parse(fs.readFileSync(INSIGHTS_FILE, 'utf-8'));
    // Extract task IDs that frequently fail from insights
    const failureReasons = insights.stats?.failureReasons || [];
    return failureReasons;
  } catch (e) {
    return [];
  }
}

// --- Task Selection (Weighted Random) ---

function selectStrategicTask(project, projectState, capabilityFilter = () => true) {
  const tasks = config.BINH_PHAP_TASKS.filter(capabilityFilter);
  const taskHistory = projectState.taskHistory || {};
  const failedIds = getFailedTaskIds();

  if (tasks.length === 0) return null;

  // Weight each task: lower count = higher weight, failed tasks get lower weight
  const weighted = tasks.map(task => {
    const runCount = taskHistory[task.id] || 0;
    const isFailed = failedIds.includes(task.id);

    // Base weight: inverse of run count (tasks run less get priority)
    let weight = Math.max(1, 10 - runCount);

    // Penalties
    if (isFailed) weight *= 0.3; // Heavily penalize known failures
    if (task.complexity === 'strategic') weight *= 0.5; // Strategic tasks are expensive

    return { task, weight };
  });

  // Weighted random selection
  const totalWeight = weighted.reduce((sum, w) => sum + w.weight, 0);
  let random = Math.random() * totalWeight;

  for (const { task, weight } of weighted) {
    random -= weight;
    if (random <= 0) return task;
  }

  // Fallback: first task
  return tasks[0];
}

// --- Mission Generation ---

function generateStrategicMission(task, project) {
  const timestamp = Date.now();
  const filename = `HIGH_mission_strategic_${task.id}_${project}_${timestamp}.txt`;
  const prompt = `COMPLEXITY: ${task.complexity || 'complex'}
PROJECT: ${project}

AGI LEVEL 6 — STRATEGIC MISSION (Proactive Improvement)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/cook "${task.cmd}

Project: ${project}
Context: Autonomously generated by Strategic Brain (Level 6 AGI).
This is a PROACTIVE improvement — no errors triggered this mission.
Focus on measurable improvements. Report findings clearly.
Respond in TIẾNG VIỆT." --auto
`;

  return { filename, prompt };
}

// --- Main Entry Point ---

/**
 * Try to dispatch a strategic mission for a GREEN project.
 * Called by auto-cto-pilot when handleScan finds 0 errors.
 *
 * @param {Object} state - auto-cto state object
 * @param {string} project - project name
 * @param {string} projectDir - project directory path
 * @returns {boolean} true if a mission was dispatched
 */
function tryStrategicMission(state, project, projectDir) {
  const strategicState = loadStrategicState();
  const projectState = strategicState[project] || {
    lastStrategicAt: null,
    taskHistory: {},
    totalStrategic: 0
  };

  // Cooldown gate: 30 min between strategic missions per project
  if (projectState.lastStrategicAt) {
    const elapsed = Date.now() - new Date(projectState.lastStrategicAt).getTime();
    if (elapsed < COOLDOWN_MS) {
      const remaining = Math.round((COOLDOWN_MS - elapsed) / 60000);
      log(`[STRATEGIC] ${project} — cooldown active (${remaining}min remaining). Skipping.`);
      return false;
    }
  }

  // Don't dispatch if task queue is not empty
  const tasks = fs.readdirSync(config.WATCH_DIR).filter(f => config.TASK_PATTERN.test(f));
  if (tasks.length > 0) {
    log(`[STRATEGIC] ${project} — task queue not empty (${tasks.length} pending). Skipping.`);
    return false;
  }

  // Check project capabilities (e.g. skip test_suite if no test script)
  const pkgPath = path.join(projectDir, 'package.json');
  let projectScripts = {};
  try {
    if (fs.existsSync(pkgPath)) {
      projectScripts = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')).scripts || {};
    }
  } catch (e) { }

  // Select best task for this project (filter by capability)
  const capabilityFilter = (task) => {
    if (task.id === 'test_suite' && !projectScripts.test) return false;
    if (task.id === 'i18n_sync' && !fs.existsSync(path.join(projectDir, 'src/i18n')) && !fs.existsSync(path.join(projectDir, 'i18n'))) return false;
    return true;
  };
  const selectedTask = selectStrategicTask(project, projectState, capabilityFilter);
  if (!selectedTask) {
    log(`[STRATEGIC] ${project} — no applicable tasks for this project's capabilities. Skipping.`);
    return false;
  }
  const { filename, prompt } = generateStrategicMission(selectedTask, project);

  // Write mission file
  const missionPath = path.join(config.WATCH_DIR, filename);
  fs.writeFileSync(missionPath, prompt);

  // Update strategic state
  projectState.lastStrategicAt = new Date().toISOString();
  projectState.taskHistory[selectedTask.id] = (projectState.taskHistory[selectedTask.id] || 0) + 1;
  projectState.totalStrategic++;
  strategicState[project] = projectState;
  saveStrategicState(strategicState);

  log(`[STRATEGIC] 🧠 Level 6 — Dispatched: ${selectedTask.id} for ${project} (total: ${projectState.totalStrategic})`);

  return true;
}

module.exports = { tryStrategicMission };
