#!/usr/bin/env python3
"""
🔑 API Setup Wizard
===================
Interactive setup for all API credentials.
Run once to configure everything.

Usage: python3 scripts/setup_apis.py
"""

import os
from pathlib import Path

EMAIL = "billwill.mentor@gmail.com"

BOLD = "\033[1m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
RESET = "\033[0m"


def print_header(title):
    print(f"\n{BOLD}{BLUE}{'=' * 60}{RESET}")
    print(f"{BOLD}{BLUE}{title}{RESET}")
    print(f"{BOLD}{BLUE}{'=' * 60}{RESET}\n")


def print_step(n, title, url):
    print(f"\n{YELLOW}Step {n}: {title}{RESET}")
    print(f"   📍 URL: {url}")
    print(f"   📧 Email: {EMAIL}")


def setup_gumroad():
    print_header("🛒 GUMROAD SETUP")
    print(f"""
{GREEN}Gumroad is already set up for billwill.mentor!{RESET}

To get your API token:
1. Go to: https://app.gumroad.com/settings/advanced
2. Scroll to "Application" section
3. Copy "Access Token"
4. Paste below:
""")
    token = input("Gumroad Access Token: ").strip()
    return {"GUMROAD_ACCESS_TOKEN": token} if token else {}


def setup_paypal():
    print_header("💳 PAYPAL SETUP")
    print_step(1, "Create PayPal Developer App", "https://developer.paypal.com/dashboard/applications")
    print(f"""
PayPal is the primary payment provider:
1. Sign up with {EMAIL}
2. Create a "REST API App"
3. Copy Client ID and Secret
""")
    client_id = input("PayPal Client ID: ").strip()
    secret = input("PayPal Secret: ").strip()
    webhook_id = input("PayPal Webhook ID (optional): ").strip()
    
    creds = {}
    if client_id: creds["PAYPAL_CLIENT_ID"] = client_id
    if secret: creds["PAYPAL_CLIENT_SECRET"] = secret
    if webhook_id: creds["PAYPAL_WEBHOOK_ID"] = webhook_id
    return creds


def setup_twitter():
    print_header("🐦 TWITTER/X SETUP")
    print_step(1, "Create Twitter Developer Account", "https://developer.twitter.com")
    print(f"""
For auto-posting tweets:
1. Apply for Developer account with {EMAIL}
2. Create a Project and App
3. Generate API Keys + Access Tokens
4. Enable "Read and Write" permissions
""")

    keys = {}
    for key in [
        "TWITTER_API_KEY",
        "TWITTER_API_SECRET",
        "TWITTER_ACCESS_TOKEN",
        "TWITTER_ACCESS_SECRET",
    ]:
        val = input(f"{key}: ").strip()
        if val:
            keys[key] = val
    return keys


def setup_discord():
    print_header("💬 DISCORD WEBHOOK")
    print("""
For notifications:
1. Open your Discord server
2. Edit Channel > Integrations > Webhooks
3. Create Webhook, copy URL
""")
    url = input("Discord Webhook URL (or Enter to skip): ").strip()
    return {"DISCORD_WEBHOOK_URL": url} if url else {}


def save_env(credentials):
    """Save credentials to .env file."""
    env_file = Path(".env")

    # Load existing
    existing = {}
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                existing[k.strip()] = v.strip()

    # Merge
    existing.update(credentials)

    # Save
    content = "# 🔑 API Credentials\n# Generated by setup_apis.py\n\n"
    for k, v in existing.items():
        content += f"{k}={v}\n"

    env_file.write_text(content)
    print(f"\n{GREEN}✅ Saved to .env{RESET}\n")


def main():
    print_header("🔑 API SETUP WIZARD")
    print(f"Email: {EMAIL}")
    print("This wizard will help you configure all APIs.\n")

    all_creds = {}

    # Gumroad
    creds = setup_gumroad()
    all_creds.update(creds)

    # PayPal (Replacing Polar)
    creds = setup_paypal()
    all_creds.update(creds)

    # Discord
    creds = setup_discord()
    all_creds.update(creds)

    # Twitter (optional)
    if input("\nSet up Twitter API? (y/N): ").lower() == "y":
        creds = setup_twitter()
        all_creds.update(creds)

    # Save
    if all_creds:
        save_env(all_creds)

        # Verify
        print_header("🔌 VERIFICATION")
        os.system("python3 scripts/api_hub.py status")
    else:
        print(f"\n{YELLOW}No credentials entered.{RESET}\n")


if __name__ == "__main__":
    main()
