// ESLint Flat Config - ESLint v9+
// https://eslint.org/docs/latest/use/configure/migration-guide

export default [
  // Global ignores
  {
    ignores: [
      'node_modules/**',
      '*.min.js',
      'coverage/**',
      'public/*.min.js',
      'js/*.min.js',
      'dashboard/*.min.js',
      'tests/**',
      'worker/**',
      'cto-brain.cjs',
      'websocket-server.js',
      'admin/**',
      'assets/**',
      'dashboard/**',
    ],
  },
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        AbortController: 'readonly',
        FormData: 'readonly',
        WebSocket: 'readonly',
        IntersectionObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        alert: 'readonly',
        prompt: 'readonly',
        confirm: 'readonly',
        // F&B Caffe Container debug flag
        FNB_DEBUG: 'readonly',
        // Service Worker globals
        self: 'readonly',
        caches: 'readonly',
        clients: 'readonly',
        // Node.js globals
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        // Web Crypto API
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        // Base64 functions (Worker environment)
        atob: 'readonly',
        btoa: 'readonly',
        // showToast global
        showToast: 'readonly',
      },
    },
    rules: {
      'indent': ['error', 2],
      'linebreak-style': ['error', 'unix'],
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'no-unused-vars': 'off',
      'no-console': 'off',
      'no-debugger': 'warn',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-undef': 'error',
      'no-implicit-globals': 'error',
      'no-multi-spaces': 'error',
      'no-trailing-spaces': 'error',
      'eol-last': 'error',
      'eqeqeq': ['error', 'smart'],
      'curly': 'error',
      'dot-notation': 'warn',
      'no-unused-expressions': 'warn',
      'no-shadow': 'warn',
      'no-throw-literal': 'error',
      'no-return-assign': 'error',
      'no-useless-return': 'warn',
      'array-callback-return': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-caller': 'error',
      'no-void': 'error',
      'prefer-promise-reject-errors': 'error',
    },
    ignores: [
      'node_modules/',
      '*.min.js',
      'coverage/',
      'public/*.min.js',
      'js/*.min.js',
      'dashboard/*.min.js',
      'tests/',
      'worker/',
      'cto-brain.cjs',
      'websocket-server.js',
      'admin/',
      'assets/',
      'dashboard/',
    ],
  },
];
