"""
create prompts table

Revision ID: 20260128_create_prompts_table
Revises: 20260128_rate_limiting
Create Date: 2026-01-28 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20260128_create_prompts_table'
down_revision = '20260128_rate_limiting'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('prompts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('input_variables', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('version', sa.Integer(), nullable=True, default=1),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_prompts_name'), 'prompts', ['name'], unique=True)
    op.create_index(op.f('idx_prompts_slug'), 'prompts', ['slug'], unique=True)
    op.create_index(op.f('idx_prompts_id'), 'prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('idx_prompts_id'), table_name='prompts')
    op.drop_index(op.f('idx_prompts_slug'), table_name='prompts')
    op.drop_index(op.f('idx_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
