"""
create rate limiting tables

Revision ID: 20260128_rate_limiting
Revises: 20260127_audit_logs
Create Date: 2026-01-28 10:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260128_rate_limiting'
down_revision = '20260127_audit_logs'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('ip_blocklist',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ip_address', sa.String(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ip_blocklist_ip_address', 'ip_blocklist', ['ip_address'], unique=True)

    op.create_table('rate_limit_violations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ip_address', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('endpoint', sa.String(), nullable=False),
        sa.Column('violation_type', sa.String(), nullable=False),
        sa.Column('request_headers', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_violations_ip_address', 'rate_limit_violations', ['ip_address'], unique=False)
    op.create_index('idx_rate_limit_violations_user_id', 'rate_limit_violations', ['user_id'], unique=False)
    op.create_index('idx_rate_limit_violations_timestamp', 'rate_limit_violations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index('idx_rate_limit_violations_timestamp', table_name='rate_limit_violations')
    op.drop_index('idx_rate_limit_violations_user_id', table_name='rate_limit_violations')
    op.drop_index('idx_rate_limit_violations_ip_address', table_name='rate_limit_violations')
    op.drop_table('rate_limit_violations')

    op.drop_index('idx_ip_blocklist_ip_address', table_name='ip_blocklist')
    op.drop_table('ip_blocklist')
    # ### end Alembic commands ###
