import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export async function exportDashboardToPDF(elementId: string, filename: string = 'dashboard-report.pdf') {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with id ${elementId} not found`);
    return;
  }

  try {
    // Show loading state or toast here if needed

    // Capture the element as a canvas
    const canvas = await html2canvas(element, {
      scale: 2, // Higher scale for better resolution
      useCORS: true, // Enable cross-origin images
      logging: false,
      backgroundColor: '#ffffff' // Ensure white background
    });

    const imgData = canvas.toDataURL('image/png');

    // Calculate PDF dimensions
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = canvas.width;
    const imgHeight = canvas.height;

    // Scale image to fit PDF width
    const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
    const imgX = (pdfWidth - imgWidth * ratio) / 2;
    const imgY = 10; // Top margin

    // Add image to PDF
    // For long dashboards, this might need pagination logic (advanced feature)
    // For now, we fit everything on one page or scale it
    const finalWidth = pdfWidth - 20; // 10mm margins
    const finalHeight = (imgHeight * finalWidth) / imgWidth;

    // Check if height exceeds page, if so, we might need multiple pages or scaling
    if (finalHeight > pdfHeight - 20) {
       // Simple approach: Scale to fit height if too tall (might be too small)
       // Or split (complex). Let's start with scale to fit width and multi-page if needed.

       let heightLeft = finalHeight;
       let position = 0;

       // First page
       pdf.addImage(imgData, 'PNG', 10, 10, finalWidth, finalHeight);
       heightLeft -= pdfHeight;

       // Extra pages
       while (heightLeft >= 0) {
         position = heightLeft - finalHeight;
         pdf.addPage();
         pdf.addImage(imgData, 'PNG', 10, position, finalWidth, finalHeight);
         heightLeft -= pdfHeight;
       }

    } else {
       pdf.addImage(imgData, 'PNG', 10, 10, finalWidth, finalHeight);
    }

    // Header / Footer
    const date = new Date().toLocaleDateString();
    pdf.setFontSize(10);
    pdf.text(`Generated by AgencyOS on ${date}`, 10, pdfHeight - 10);

    pdf.save(filename);

  } catch (error) {
    console.error('Export failed:', error);
    throw error;
  }
}

export async function exportDashboardToPNG(elementId: string, filename: string = 'dashboard-snapshot.png') {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff'
    });

    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL('image/png');
    link.click();
  } catch (error) {
    console.error('PNG export failed:', error);
    throw error;
  }
}
