"""
Manifest Generator - Automated updates for QUANTUM_MANIFEST.md.
"""
from pathlib import Path
from antigravity.core.knowledge.rule_registry import rule_registry

MANIFEST_PATH = Path(".claude/docs/QUANTUM_MANIFEST.md")

TEMPLATE = """# 🔮 QUANTUM MANIFEST - Antigravity Context Core

> **"Lượng Tử Hóa" toàn bộ năng lực Agent vào một file duy nhất**

---

## 🏯 CONSTITUTION (Rules Above All)

{rules_section}

---

## 🤖 AGENT ARMY (Dynamic Inventory)

| Rule File | Applied Agents |
|-----------|----------------|
{agent_mapping_section}

---

## ⚡ TURBO COMMANDS (Auto-Run Safe)

```yaml
# These commands are safe to auto-run (// turbo annotation)
- /context-prime # Load full context
- /test # Run test suite
- /scout # Codebase reconnaissance
- /cook # Development mode
```

---

## 🎯 SESSION ACTIVATION SEQUENCE

```
1. Agent reads QUANTUM_MANIFEST.md (this file)
2. Context loaded: {rule_count} rules indexed
3. WIN-WIN-WIN gate activated
4. Model: Gemini 3 Flash (1M context)
5. Ready for mission 🚀
```

---

_Generated by Antigravity ManifestGenerator | 2026-01-20_
"""

def generate_manifest():
    """Generates the QUANTUM_MANIFEST.md based on the RuleRegistry."""
    rule_registry.refresh()

    # 1. Rules Section
    rules_section = ""
    for name, meta in rule_registry.rules.items():
        rules_section += f"### {meta.get('title', name)}\n"
        rules_section += f"- **File**: `{name}`\n"
        rules_section += f"- **Tags**: `{', '.join(meta.get('tags', []))}`\n"
        rules_section += f"- **Agents**: `{', '.join(meta.get('agents', []))}`\n\n"

    # 2. Agent Mapping Section
    mapping_section = ""
    for name, meta in rule_registry.rules.items():
        agents = ", ".join([f"`{a}`" for a in meta.get("agents", [])])
        mapping_section += f"| `{name}` | {agents} |\n"

    content = TEMPLATE.format(
        rules_section=rules_section,
        agent_mapping_section=mapping_section,
        rule_count=len(rule_registry.rules)
    )

    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(content, encoding="utf-8")
    print(f"✅ QUANTUM_MANIFEST.md updated with {len(rule_registry.rules)} rules.")

if __name__ == "__main__":
    generate_manifest()
