"""Mekong Webhook Schema - Pydantic models for webhook event payloads.

SPRINT 3 - Task 3.3: Define all webhook event payloads per mekong-agencyos-roadmap.md
All events AgencyOS receives from Mekong CLI engine.

Usage:
    from src.core.webhook_schema import MissionCreatedPayload, MissionCompletedPayload
    payload = MissionCreatedPayload(mission_id="...", goal="...")
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal, Union
from pydantic import BaseModel, Field


class BaseWebhookPayload(BaseModel):
    """Base class for all webhook payloads."""

    event_type: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    version: str = "1.0"


# =============================================================================
# MISSION LIFECYCLE EVENTS
# =============================================================================


class MissionCreatedPayload(BaseWebhookPayload):
    """Payload for mission.created event.

    Sent when a mission is created and queued for execution.
    """

    event_type: Literal["mission.created"] = "mission.created"
    mission_id: str = Field(..., description="Unique mission identifier")
    goal: str = Field(..., description="The goal to achieve")
    tenant_id: str = Field(..., description="Tenant identifier")
    priority: Literal["low", "normal", "high"] = "normal"
    status: str = "pending"
    estimated_steps: int = Field(default=0, description="Estimated number of steps")


class MissionPlanningPayload(BaseWebhookPayload):
    """Payload for mission.planning event.

    Sent when plan steps are generated by the Planner.
    """

    event_type: Literal["mission.planning"] = "mission.planning"
    mission_id: str
    goal: str
    plan_steps: list[dict[str, Any]] = Field(
        default_factory=list,
        description="List of plan steps with task, dependencies, verification",
    )
    estimated_duration_seconds: int = Field(default=0, description="Estimated duration")


# =============================================================================
# STEP EXECUTION EVENTS
# =============================================================================


class MissionStepStartedPayload(BaseWebhookPayload):
    """Payload for mission.step.started event.

    Sent when a step execution begins.
    """

    event_type: Literal["mission.step.started"] = "mission.step.started"
    mission_id: str
    step_id: str = Field(..., description="Step identifier")
    step_number: int = Field(..., description="Step sequence number")
    step_description: str = Field(..., description="Human-readable step description")
    agent_name: str = Field(default="", description="Agent executing the step")


class MissionStepCompletedPayload(BaseWebhookPayload):
    """Payload for mission.step.completed event.

    Sent when a step completes successfully.
    """

    event_type: Literal["mission.step.completed"] = "mission.step.completed"
    mission_id: str
    step_id: str
    step_number: int
    result: dict[str, Any] = Field(
        default_factory=dict,
        description="Step execution result (files, outputs, metrics)",
    )
    duration_seconds: float = Field(default=0.0, description="Step execution time")
    artifacts: list[str] = Field(
        default_factory=list,
        description="List of files or artifacts created",
    )


class MissionStepFailedPayload(BaseWebhookPayload):
    """Payload for mission.step.failed event.

    Sent when a step fails (includes retry info).
    """

    event_type: Literal["mission.step.failed"] = "mission.step.failed"
    mission_id: str
    step_id: str
    step_number: int
    error: str = Field(..., description="Error message")
    error_type: str = Field(default="unknown", description="Error type/category")
    retry_count: int = Field(default=0, description="Number of retries attempted")
    max_retries: int = Field(default=3, description="Maximum retries allowed")
    can_retry: bool = Field(default=True, description="Whether retry is possible")
    retry_after_seconds: int = Field(
        default=0, description="Seconds to wait before retry"
    )


# =============================================================================
# MISSION COMPLETION EVENTS
# =============================================================================


class MissionCompletedPayload(BaseWebhookPayload):
    """Payload for mission.completed event.

    Sent when mission completes successfully (includes files, metrics).
    """

    event_type: Literal["mission.completed"] = "mission.completed"
    mission_id: str
    goal: str
    status: Literal["completed"] = "completed"
    result: dict[str, Any] = Field(
        default_factory=dict,
        description="Final result with all outputs",
    )
    files_created: list[str] = Field(
        default_factory=list,
        description="List of files created during execution",
    )
    total_steps: int = Field(default=0, description="Total steps executed")
    total_duration_seconds: float = Field(
        default=0.0, description="Total mission duration"
    )
    metrics: dict[str, Any] = Field(
        default_factory=dict,
        description="Performance metrics (success_rate, retry_count, etc.)",
    )
    credits_consumed: int = Field(default=0, description="Credits used for this mission")


class MissionFailedPayload(BaseWebhookPayload):
    """Payload for mission.failed event.

    Sent when mission fails after retries exhausted (includes error + refund trigger).
    """

    event_type: Literal["mission.failed"] = "mission.failed"
    mission_id: str
    goal: str
    status: Literal["failed"] = "failed"
    error: str = Field(..., description="Final error message")
    error_type: str = Field(default="unknown", description="Error type/category")
    failed_at_step: int = Field(default=0, description="Step number where failure occurred")
    total_steps_completed: int = Field(default=0, description="Steps completed before failure")
    retry_attempts: int = Field(default=0, description="Total retry attempts")
    refund_eligible: bool = Field(
        default=True, description="Whether credits should be refunded"
    )
    credits_to_refund: int = Field(default=0, description="Credits to refund")


# =============================================================================
# TENANT EVENTS
# =============================================================================


class CreditsLowPayload(BaseWebhookPayload):
    """Payload for credits.low event.

    Sent when tenant balance falls below threshold.
    """

    event_type: Literal["credits.low"] = "credits.low"
    tenant_id: str
    current_balance: int = Field(..., description="Current credit balance")
    threshold: int = Field(default=10, description="Low balance threshold")
    currency: str = Field(default="credits", description="Currency type")
    top_up_url: str = Field(
        default="", description="URL to top up credits"
    )


# =============================================================================
# UTILITY CLASSES
# =============================================================================


class WebhookEventSchema(BaseModel):
    """Schema documentation for webhook events."""

    event_type: str
    description: str
    payload_class: str
    when_sent: str


WEBHOOK_EVENT_SCHEMAS: list[WebhookEventSchema] = [
    WebhookEventSchema(
        event_type="mission.created",
        description="Mission created and queued for execution",
        payload_class="MissionCreatedPayload",
        when_sent="Immediately after POST /v1/missions",
    ),
    WebhookEventSchema(
        event_type="mission.planning",
        description="Plan steps generated by LLM planner",
        payload_class="MissionPlanningPayload",
        when_sent="After planner generates task steps",
    ),
    WebhookEventSchema(
        event_type="mission.step.started",
        description="A step execution started",
        payload_class="MissionStepStartedPayload",
        when_sent="Before executing each plan step",
    ),
    WebhookEventSchema(
        event_type="mission.step.completed",
        description="A step completed successfully",
        payload_class="MissionStepCompletedPayload",
        when_sent="After step verification passes",
    ),
    WebhookEventSchema(
        event_type="mission.step.failed",
        description="A step failed (includes retry info)",
        payload_class="MissionStepFailedPayload",
        when_sent="After step fails, before retry or abort",
    ),
    WebhookEventSchema(
        event_type="mission.completed",
        description="Mission completed successfully",
        payload_class="MissionCompletedPayload",
        when_sent="After all steps complete and verify",
    ),
    WebhookEventSchema(
        event_type="mission.failed",
        description="Mission failed after retries exhausted",
        payload_class="MissionFailedPayload",
        when_sent="After all retries exhausted or critical error",
    ),
    WebhookEventSchema(
        event_type="credits.low",
        description="Tenant credit balance below threshold",
        payload_class="CreditsLowPayload",
        when_sent="When balance < threshold (default 10)",
    ),
]


# =============================================================================
# TYPE ALIASES FOR EASE OF USE
# =============================================================================

MissionEventPayload = Union[
    MissionCreatedPayload,
    MissionPlanningPayload,
    MissionStepStartedPayload,
    MissionStepCompletedPayload,
    MissionStepFailedPayload,
    MissionCompletedPayload,
    MissionFailedPayload,
    CreditsLowPayload,
]


def get_payload_class(event_type: str) -> type[BaseWebhookPayload] | None:
    """Get payload class for an event type.

    Args:
        event_type: The webhook event type (e.g., "mission.created")

    Returns:
        Payload class or None if not found
    """
    mapping: dict[str, type[BaseWebhookPayload]] = {
        "mission.created": MissionCreatedPayload,
        "mission.planning": MissionPlanningPayload,
        "mission.step.started": MissionStepStartedPayload,
        "mission.step.completed": MissionStepCompletedPayload,
        "mission.step.failed": MissionStepFailedPayload,
        "mission.completed": MissionCompletedPayload,
        "mission.failed": MissionFailedPayload,
        "credits.low": CreditsLowPayload,
    }
    return mapping.get(event_type)


__all__ = [
    # Base
    "BaseWebhookPayload",
    # Mission lifecycle
    "MissionCreatedPayload",
    "MissionPlanningPayload",
    # Step execution
    "MissionStepStartedPayload",
    "MissionStepCompletedPayload",
    "MissionStepFailedPayload",
    # Mission completion
    "MissionCompletedPayload",
    "MissionFailedPayload",
    # Tenant
    "CreditsLowPayload",
    # Utility
    "WebhookEventSchema",
    "WEBHOOK_EVENT_SCHEMAS",
    "MissionEventPayload",
    "get_payload_class",
]
