"""
Report Generator Agent - Automated Reporting
Generates weekly/monthly reports and KPI summaries.
"""

from dataclasses import dataclass, field
from typing import List, Dict
from datetime import datetime, timedelta
from enum import Enum
import random


class ReportType(Enum):
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    CUSTOM = "custom"


class ReportFormat(Enum):
    TEXT = "text"
    HTML = "html"
    PDF = "pdf"


@dataclass
class Report:
    """Generated report"""
    id: str
    title: str
    report_type: ReportType
    period_start: datetime
    period_end: datetime
    content: str
    metrics: Dict = field(default_factory=dict)
    format: ReportFormat = ReportFormat.TEXT
    created_at: datetime = None

    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now()


class ReportGeneratorAgent:
    """
    Report Generator Agent - Tạo Báo cáo Tự động
    
    Responsibilities:
    - Generate periodic reports
    - Summarize KPIs
    - Export to various formats
    - Schedule reports
    """

    # Report templates
    TEMPLATES = {
        ReportType.WEEKLY: """
# 📊 Weekly Report: {title}
Period: {start} → {end}

## Key Metrics
{metrics_section}

## Highlights
{highlights}

## Action Items
{action_items}

---
Generated by Mekong-CLI Report Agent
""",
        ReportType.MONTHLY: """
# 📈 Monthly Report: {title}
Period: {start} → {end}

## Executive Summary
{summary}

## KPIs
{metrics_section}

## Performance
{performance}

## Next Month Focus
{focus}

---
Generated by Mekong-CLI Report Agent
"""
    }

    def __init__(self):
        self.name = "Report Generator"
        self.status = "ready"
        self.reports: Dict[str, Report] = {}

    def generate_weekly(
        self,
        title: str,
        metrics: Dict,
        highlights: List[str] = None,
        action_items: List[str] = None
    ) -> Report:
        """Generate weekly report"""
        end_date = datetime.now()
        start_date = end_date - timedelta(days=7)

        metrics_section = "\n".join([
            f"- **{k}**: {v}" for k, v in metrics.items()
        ])

        highlights_section = "\n".join([
            f"- {h}" for h in (highlights or ["No highlights this week"])
        ])

        actions_section = "\n".join([
            f"- [ ] {a}" for a in (action_items or ["No action items"])
        ])

        content = self.TEMPLATES[ReportType.WEEKLY].format(
            title=title,
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d"),
            metrics_section=metrics_section,
            highlights=highlights_section,
            action_items=actions_section
        )

        report_id = f"report_{int(datetime.now().timestamp())}_{random.randint(100,999)}"

        report = Report(
            id=report_id,
            title=title,
            report_type=ReportType.WEEKLY,
            period_start=start_date,
            period_end=end_date,
            content=content,
            metrics=metrics
        )

        self.reports[report_id] = report
        return report

    def generate_monthly(
        self,
        title: str,
        metrics: Dict,
        summary: str = "",
        performance: str = "",
        focus: str = ""
    ) -> Report:
        """Generate monthly report"""
        end_date = datetime.now()
        start_date = end_date - timedelta(days=30)

        metrics_section = "\n".join([
            f"| {k} | {v} |" for k, v in metrics.items()
        ])
        metrics_section = "| Metric | Value |\n|--------|-------|\n" + metrics_section

        content = self.TEMPLATES[ReportType.MONTHLY].format(
            title=title,
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d"),
            summary=summary or "Summary not provided",
            metrics_section=metrics_section,
            performance=performance or "Performance analysis pending",
            focus=focus or "Focus areas to be determined"
        )

        report_id = f"report_{int(datetime.now().timestamp())}_{random.randint(100,999)}"

        report = Report(
            id=report_id,
            title=title,
            report_type=ReportType.MONTHLY,
            period_start=start_date,
            period_end=end_date,
            content=content,
            metrics=metrics
        )

        self.reports[report_id] = report
        return report

    def get_recent_reports(self, count: int = 5) -> List[Report]:
        """Get most recent reports"""
        return sorted(
            self.reports.values(),
            key=lambda r: r.created_at,
            reverse=True
        )[:count]

    def get_stats(self) -> Dict:
        """Get report statistics"""
        reports = list(self.reports.values())

        return {
            "total_reports": len(reports),
            "by_type": {
                rt.value: len([r for r in reports if r.report_type == rt])
                for rt in ReportType
            },
            "this_month": len([
                r for r in reports
                if r.created_at.month == datetime.now().month
            ])
        }


# Demo
if __name__ == "__main__":
    agent = ReportGeneratorAgent()

    print("📊 Report Generator Agent Demo\n")

    # Generate weekly report
    weekly = agent.generate_weekly(
        title="Marketing Performance",
        metrics={
            "Leads Generated": 156,
            "Conversion Rate": "12.5%",
            "Revenue": "$8,500",
            "CAC": "$45"
        },
        highlights=[
            "Launched new landing page",
            "Email campaign hit 35% open rate",
            "Social reach up 25%"
        ],
        action_items=[
            "A/B test CTA buttons",
            "Review ad spend allocation"
        ]
    )

    print(f"📄 Report: {weekly.title}")
    print(f"   Type: {weekly.report_type.value}")
    print(f"   Period: {weekly.period_start.strftime('%m/%d')} - {weekly.period_end.strftime('%m/%d')}")

    print("\n📋 Content Preview:")
    print(weekly.content[:300] + "...")

    # Stats
    print("\n📊 Stats:")
    stats = agent.get_stats()
    print(f"   Total Reports: {stats['total_reports']}")
