"""Plugin management Typer sub-app — E1c of Track E.

Registers the ``mekong plugin`` command group with ``init`` as the first
sub-command. Future Waves E2–E4 add ``install``, ``list``, ``remove``,
``update``, ``search``, and ``info``.

Usage in ``app_setup.py``::

 from src.cli.commands.plugin import register as register_plugin
 register_plugin(root)
"""

from __future__ import annotations

from pathlib import Path

import typer


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def register(cli: typer.Typer) -> None:
 """Register ``mekong plugin`` sub-app."""

 app = typer.Typer(
  name="plugin",
  help="Plugin ecosystem: init / install / list / remove / update",
  no_args_is_help=True,
  add_completion=False,
  rich_markup_mode="rich",
 )

 _register_init(app)

 cli.add_typer(app, name="plugin", help="Plugin ecosystem management")


# ---------------------------------------------------------------------------
# init
# ---------------------------------------------------------------------------

_PLUGIN_TYPES = ("agent", "provider", "hook", "recipe")
"""Valid values for the ``--type`` option."""

# NOTE: braces in the JSON body are doubled ({{ }}) because we call
# .format() below. Single braces would be interpreted as format fields.
_PLUGIN_JSON_TEMPLATE = """\
{{
 "id": "com.yourorg.{name}",
 "name": "{name_clean}",
 "version": "0.1.0",
 "description": "{description}",
 "author": "",
 "license": "MIT",
 "engines": {{ "mekong": "^6.0.0" }},
 "permissions": [],
 "mcu_cost": 1,
 "dependencies": [],
 "hooks": [],
 "isolation": "none"
}}
"""

_INIT_PY_TEMPLATE = """\
\"\"\"{name_clean} — Mekong CLI plugin entry point.

The ``register()`` function is called by the plugin loader when this plugin
is activated. Register commands via the provided *registry*.
\"\"\"


def register(registry) -> None:
 \"\"\"Register plugin commands and hooks with the runtime registry.

 Args:
  registry: PluginRuntime command + hook registry.
 \"\"\"
 # TODO: register your commands here.
 # registry.register_command(CommandSpec(...))
 pass
"""

_README_TEMPLATE = """\
# {name_clean}

> Generated by `mekong plugin init`.

## Structure

``` .
├── .plugin.json # manifest (required)
├── src/
│   └── __init__.py # register() entry point
├── README.md # this file
└── tests/
```

## Next Steps

1. Edit `.plugin.json` to fill in id, description, author.
2. Implement commands in `src/__init__.py`.
3. Run `mekong plugin list` to verify registration.
"""

INIT_TEST_TEMPLATE = """\
# tests/__init__.py — smoke tests for {name_clean}
"""


def _title_to_kebab(name: str) -> str:
 return name.strip().lower().replace(" ", "-").replace("_", "-")


def _scaffold_plugin(
 target_dir: Path,
 name: str,
 plugin_type: str,
 description: str,
) -> None:
 """Create plugin directory tree with manifest, source, and tests."""

 name_clean = _title_to_kebab(name)
 target_dir.mkdir(parents=True, exist_ok=False)

 src_dir = target_dir / "src"
 src_dir.mkdir()

 tests_dir = target_dir / "tests"
 tests_dir.mkdir()

 # .plugin.json
 plugin_json = target_dir / ".plugin.json"
 plugin_json.write_text(
  _PLUGIN_JSON_TEMPLATE.format(
   name=name_clean,
   name_clean=name_clean,
   description=description or f"{name_clean} plugin",
  ),
  encoding="utf-8",
 )

 # src/__init__.py
 (src_dir / "__init__.py").write_text(
  _INIT_PY_TEMPLATE.format(name_clean=name_clean),
  encoding="utf-8",
 )

 # README.md
 (target_dir / "README.md").write_text(
  _README_TEMPLATE.format(name_clean=name_clean),
  encoding="utf-8",
 )

 # tests/__init__.py
 (tests_dir / "__init__.py").write_text(
  INIT_TEST_TEMPLATE.format(name_clean=name_clean),
  encoding="utf-8",
 )


def _register_init(app: typer.Typer) -> None:

 @app.command("init")
 def init_cmd(
  name: str = typer.Argument(..., help="Plugin name (used as directory name)"),
  type: str = typer.Option(
   "agent",
   "--type",
   "-t",
   help="Plugin type",
  ),
  description: str = typer.Option(
   "",
   "--description",
   "-d",
   help="Short description for the manifest",
  ),
  output_dir: str = typer.Option(
   ".",
   "--dir",
   help="Parent directory for the new plugin",
  ),
 ) -> None:
  """Scaffold a new Mekong CLI plugin.

  Creates a new directory with:

  * ``.plugin.json`` — validated manifest
  * ``src/__init__.py`` — ``register()`` entry point stub
  * ``README.md`` — project documentation
  * ``tests/`` — test directory

  Example::

   mekong plugin init my-plugin --type agent --dir ./plugins
  """

  if type not in _PLUGIN_TYPES:
   typer.echo(
    f"Error: --type must be one of: {', '.join(_PLUGIN_TYPES)}",
    err=True,
   )
   raise typer.Exit(code=1)

  name_clean = _title_to_kebab(name)
  target = Path(output_dir).resolve() / name_clean

  if target.exists():
   typer.echo(
    f"Error: {target} already exists. Remove it first or pick a different --dir.",
    err=True,
   )
   raise typer.Exit(code=1)

  try:
   _scaffold_plugin(target, name, type, description)
  except FileExistsError:
   typer.echo(f"Error: {target} already exists.", err=True)
   raise typer.Exit(code=1)

  typer.echo(f"Plugin scaffolded at: {target}")
  typer.echo("Next: edit .plugin.json, then implement src/__init__.py::register()")


__all__ = ["register"]
