/**
 * Interactive setup wizard — Customer enters API key, .env auto-generated.
 * Uses Node.js readline (zero extra deps). Smart defaults for all non-key vars.
 */

import { Command } from 'commander';
import * as readline from 'readline';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { logger } from '../utils/logger';

const ENV_PATH = path.resolve(process.cwd(), '.env');

interface ExchangeKeys {
  id: string;
  apiKey: string;
  secret: string;
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

function buildEnvContent(exchanges: ExchangeKeys[], options: {
  tradingPair: string;
  telegramToken: string;
  telegramChat: string;
}): string {
  const lines: string[] = [
    '# Auto-generated by algo-trader setup wizard',
    `# Created: ${new Date().toISOString()}`,
    '',
    '# ─── Exchange API Keys ─────────────────────────────────',
  ];

  for (const ex of exchanges) {
    const prefix = ex.id.toUpperCase();
    lines.push(`${prefix}_API_KEY=${ex.apiKey}`);
    lines.push(`${prefix}_SECRET=${ex.secret}`);
  }

  // Legacy single-exchange (first configured exchange)
  if (exchanges.length > 0) {
    lines.push('');
    lines.push(`EXCHANGE_ID=${exchanges[0].id}`);
    lines.push(`EXCHANGE_API_KEY=${exchanges[0].apiKey}`);
    lines.push(`EXCHANGE_SECRET=${exchanges[0].secret}`);
  }

  lines.push('');
  lines.push('# ─── Trading Configuration ─────────────────────────────');
  lines.push(`TRADING_PAIR=${options.tradingPair}`);
  lines.push('TIMEFRAME=1h');
  lines.push('RSI_PERIOD=14');
  lines.push('SMA_SHORT=20');
  lines.push('SMA_LONG=50');

  lines.push('');
  lines.push('# ─── Risk Management ───────────────────────────────────');
  lines.push('MAX_POSITION_SIZE=0.01');
  lines.push('STOP_LOSS_PCT=2.0');
  lines.push('TAKE_PROFIT_PCT=5.0');
  lines.push('MAX_DAILY_LOSS=100');

  if (options.telegramToken) {
    lines.push('');
    lines.push('# ─── Telegram Alerts ──────────────────────────────────');
    lines.push(`TELEGRAM_BOT_TOKEN=${options.telegramToken}`);
    lines.push(`TELEGRAM_CHAT_ID=${options.telegramChat}`);
  }

  lines.push('');
  lines.push('# ─── Infrastructure (auto-configured) ─────────────────');
  lines.push('DATABASE_URL=postgresql://algo_trader:algo_trader_dev@localhost:5432/algo_trader');
  lines.push('REDIS_URL=redis://localhost:6379');
  lines.push('API_PORT=3000');
  lines.push('METRICS_ENABLED=true');

  lines.push('');
  lines.push('# ─── Monitoring ────────────────────────────────────────');
  lines.push('LOG_LEVEL=info');
  lines.push('LOG_FILE=algo-trader.log');
  lines.push(`GRAFANA_PASSWORD=${crypto.randomBytes(16).toString('hex')}`);

  lines.push('');
  lines.push('# ─── Feature Flags ────────────────────────────────────');
  lines.push('ENABLE_BACKTESTING=true');
  lines.push('ENABLE_LIVE_TRADING=false');

  lines.push('');

  return lines.join('\n');
}

export async function runSetupWizard(): Promise<void> {
  if (!process.stdin.isTTY) {
    logger.error('Setup wizard requires an interactive terminal. Use cp .env.example .env for non-interactive setup.');
    process.exit(1);
  }

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const sigintHandler = (): void => {
    console.log('\nSetup cancelled.');
    rl.close();
    process.exit(0);
  };
  process.once('SIGINT', sigintHandler);

  console.log('');
  console.log('╔══════════════════════════════════════════════╗');
  console.log('║     AGI Algo Trader — Setup Wizard           ║');
  console.log('╚══════════════════════════════════════════════╝');
  console.log('');

  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await ask(rl, '⚠️  .env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Existing .env preserved.');
      rl.close();
      return;
    }
  }

  const exchanges: ExchangeKeys[] = [];
  const exchangeList = ['binance', 'okx', 'bybit'];

  console.log('Configure your exchange API keys (Enter to skip):');
  console.log('');

  for (const id of exchangeList) {
    const label = id.charAt(0).toUpperCase() + id.slice(1);
    const apiKey = await ask(rl, `  ${label} API Key: `);

    if (apiKey.trim()) {
      if (apiKey.trim().length < 10) {
        console.log(`  ⚠️  Key looks too short — skipping ${label}`);
        continue;
      }
      const secret = await ask(rl, `  ${label} Secret: `);
      if (secret.trim().length < 10) {
        console.log(`  ⚠️  Secret looks too short — skipping ${label}`);
        continue;
      }
      exchanges.push({ id, apiKey: apiKey.trim(), secret: secret.trim() });
      console.log(`  ✓ ${label} configured`);
    }
  }

  if (exchanges.length === 0) {
    console.log('');
    console.log('  No exchange keys entered — backtest & dry-run still work!');
  }

  console.log('');
  const tradingPair = await ask(rl, 'Trading pair (default BTC/USDT): ');

  console.log('');
  const wantTelegram = await ask(rl, 'Setup Telegram alerts? (y/N): ');
  let telegramToken = '';
  let telegramChat = '';

  if (wantTelegram.toLowerCase() === 'y') {
    telegramToken = (await ask(rl, '  Bot Token: ')).trim();
    telegramChat = (await ask(rl, '  Chat ID: ')).trim();
  }

  process.removeListener('SIGINT', sigintHandler);
  rl.close();

  const envContent = buildEnvContent(exchanges, {
    tradingPair: tradingPair.trim() || 'BTC/USDT',
    telegramToken,
    telegramChat,
  });

  fs.writeFileSync(ENV_PATH, envContent, 'utf-8');

  console.log('');
  console.log('✅ .env created successfully!');
  console.log('');
  console.log('Quick start commands:');
  console.log('  npx ts-node src/index.ts quickstart     # Demo backtest');
  console.log('  npx ts-node src/index.ts backtest        # Full backtest');
  console.log('  npx ts-node src/index.ts arb:agi         # AGI arbitrage');
  console.log('');
}

export function registerSetupCommand(program: Command): void {
  program
    .command('setup')
    .description('Interactive setup wizard — enter API keys, auto-configure everything')
    .action(async () => {
      try {
        await runSetupWizard();
      } catch (error: unknown) {
        logger.error(`Setup failed: ${error instanceof Error ? error.message : String(error)}`);
        process.exit(1);
      }
    });
}
