import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
            type: 'autogenerated',
            dirName: 'guides',
        }
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/authentication',
        'api/rate-limiting',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
          {
              type: 'autogenerated',
              dirName: 'architecture',
          }
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
          {
              type: 'autogenerated',
              dirName: 'deployment',
          }
      ],
    },
     {
      type: 'category',
      label: 'Contributing',
      items: [
          {
              type: 'autogenerated',
              dirName: 'contributing',
          }
      ],
    },
    'changelog',
  ],
};

export default sidebars;
