/**
 * Type Definitions - RaaS UX Kit v2.1.79
 * TypeScript types for robot interface components
 */

// Robot types (core)
export type {
  Robot,
  RobotType,
  RobotDimensions,
  RobotLocation,
  RobotStatus,
  RobotMode,
  RobotConnectionState,
  BatteryStatus,
  BatteryHealth,
  SignalStatus,
  SignalType,
  SignalQuality,
  TemperatureStatus,
  TemperatureState,
  TemperatureZone,
  RobotEvent,
  EventType,
  EventLevel,
  ControlPanelProps,
  NotificationProps,
  NotificationContainerProps,
  NotificationAction,
  NotificationType,
  NotificationPosition,
  NotificationSize,
  NotificationState,
  StatusBadgeProps,
  ButtonProps,
  ButtonVariant,
  ButtonSize,
  BadgeProps,
  BadgeVariant,
  BadgeSize,
  IconProps,
  IconSize,
  IconColor,
  InputProps,
  InputType,
  InputSize,
  TextareaProps,
  SelectProps,
  SelectOption,
  ToggleProps,
  SliderProps,
  TimeRange,
  Point,
  Dimensions,
  Position,
  Theme,
  ThemeContextType,
} from './robot';

// Telemetry types
export type {
  TelemetryStream,
  TelemetryStreamType,
  TimeSeriesPoint,
  ChartConfig,
  ChartStream,
  AxisConfig,
  Annotation,
  TelemetryDashboardProps,
  StatCardProps,
  MetricType,
  MetricThresholds,
  Trend,
} from './telemetry';

// Mission types
export type {
  Mission,
  MissionType,
  MissionStatus,
  MissionPriority,
  Waypoint,
  Position3D,
  WaypointAction,
  MissionAction,
  ActionType,
  WaypointStatus,
  MissionProgress,
  MissionLog,
  LogLevel,
  MissionLogFilter,
  MissionControlProps,
  MissionTemplate,
  TemplateWaypoint,
  TemplateAction,
  MissionWebSocketEvent,
  MissionWebSocketEventType,
  MissionUpdate,
  QueuedAction,
  QueuedActionType,
  QueuedActionStatus,
  MissionStatistics,
  UseMissionControlOptions,
  UseMissionControlReturn,
} from './mission';

// Fleet types
export type {
  SearchFilter,
  FilterChip,
  SearchBarProps,
  FleetCardProps,
  FleetGridProps,
  FleetFilter,
  FleetSort,
  FleetPagination,
  FleetState,
  FleetStatus,
  FleetViewMode,
  FleetSortField,
  FleetSortOrder,
  SearchCategory,
  SearchVariant,
} from './fleet';
